/* =========================================================
   GastroCuida — Base de conteúdo
   Guia alimentar, chás, receitas, safra e dicas para quem
   convive com gastrite e refluxo (DRGE).
   Conteúdo educativo — não substitui orientação médica.
   ========================================================= */

// Status possíveis: "ok" (pode), "mod" (com moderação), "no" (evitar), "care" (cautela/orientação médica)
const STATUS = {
  ok:   { label: "Pode",       icon: "✅" },
  mod:  { label: "Moderação",  icon: "⚠️" },
  no:   { label: "Evitar",     icon: "🚫" },
  care: { label: "Cautela",    icon: "❗" },
};

const FOOD_CATEGORIES = [
  { id: "carnes",   name: "Carnes & Peixes",      icon: "🍗" },
  { id: "ovos",     name: "Ovos",                 icon: "🥚" },
  { id: "frutas",   name: "Frutas",               icon: "🍌" },
  { id: "legumes",  name: "Verduras & Legumes",   icon: "🥕" },
  { id: "raizes",   name: "Raízes & Tubérculos",  icon: "🍠" },
  { id: "graos",    name: "Grãos, Pães & Cereais",icon: "🌾" },
  { id: "laticinios", name: "Laticínios",         icon: "🥛" },
  { id: "chas",     name: "Chás & Ervas",         icon: "🍵" },
  { id: "bebidas",  name: "Bebidas",              icon: "🥤" },
  { id: "temperos", name: "Temperos",             icon: "🧂" },
  { id: "doces",    name: "Doces & Sobremesas",   icon: "🍮" },
];

const FOODS = [
  // ---------------- CARNES & PEIXES ----------------
  { cat: "carnes", name: "Frango sem pele", status: "ok",
    note: "Grelhado, cozido, desfiado ou na airfryer. A proteína mais amiga do estômago — sempre sem a pele e sem fritar." },
  { cat: "carnes", name: "Tilápia, merluza, pescada (peixes brancos)", status: "ok",
    note: "Assados, cozidos ou em papelote. Digestão leve e rápida — ótimos para o jantar." },
  { cat: "carnes", name: "Carne bovina magra (patinho, músculo, lagarto)", status: "ok",
    note: "Cozida, assada ou moída refogada com pouco óleo. Retire toda a gordura aparente." },
  { cat: "carnes", name: "Salmão", status: "mod",
    note: "Rico em ômega-3, mas mais gorduroso. Grelhado, em porções pequenas, e observe como você reage." },
  { cat: "carnes", name: "Sardinha fresca assada", status: "mod",
    note: "Boa fonte de ômega-3. Prefira fresca e assada; evite a enlatada em óleo." },
  { cat: "carnes", name: "Lombo suíno magro", status: "mod",
    note: "É o corte magro do porco. Assado e em pouca quantidade. Evite os cortes gordos." },
  { cat: "carnes", name: "Carnes gordas (picanha, cupim, costela)", status: "no",
    note: "Gordura retarda o esvaziamento do estômago e relaxa a válvula que segura o refluxo." },
  { cat: "carnes", name: "Frituras e milanesas", status: "no",
    note: "Fritura é um dos maiores gatilhos de azia. Troque pela airfryer ou forno." },
  { cat: "carnes", name: "Embutidos (linguiça, salsicha, bacon, presunto, salame, mortadela)", status: "no",
    note: "Gordura + sal + conservantes irritam a mucosa. Inclui peito de peru de pacote." },
  { cat: "carnes", name: "Carnes defumadas e churrasco com muita gordura", status: "no",
    note: "Defumação e gordura queimada agridem o estômago inflamado." },

  // ---------------- OVOS ----------------
  { cat: "ovos", name: "Ovo cozido", status: "ok",
    note: "A forma mais leve. Cozinhe 8–10 min. Vai bem no lanche, na salada e no prato principal." },
  { cat: "ovos", name: "Ovo pochê", status: "ok",
    note: "Cozido na água sem nenhuma gordura. Fica cremoso e é super digesto." },
  { cat: "ovos", name: "Ovo mexido cremoso (sem gordura)", status: "ok",
    note: "Na frigideira antiaderente, fogo baixo, mexendo sempre. Sem manteiga ou com 1 fio de azeite." },
  { cat: "ovos", name: "Omelete de forno ou frigideira antiaderente", status: "ok",
    note: "Com legumes permitidos (abobrinha, cenoura, espinafre). Asse ou use pouquíssimo azeite." },
  { cat: "ovos", name: "Crepioca (ovo + tapioca)", status: "ok",
    note: "Mistura moderna e prática: 1 ovo + 2 col. de goma de tapioca. Recheie com queijo branco." },
  { cat: "ovos", name: "Ovo frito em óleo ou manteiga", status: "no",
    note: "A gordura da fritura é o problema, não o ovo. Prefira as versões acima." },

  // ---------------- FRUTAS ----------------
  { cat: "frutas", name: "Banana (prata, nanica) madura", status: "ok",
    note: "Suave e levemente alcalina, protege a mucosa. Ótima para lanches e receitas." },
  { cat: "frutas", name: "Mamão", status: "ok",
    note: "Tem papaína, enzima que ajuda a digestão. Excelente no café da manhã." },
  { cat: "frutas", name: "Melão", status: "ok",
    note: "Pouco ácido e hidratante. Vai bem em qualquer hora do dia." },
  { cat: "frutas", name: "Pera", status: "ok",
    note: "Leve e rica em fibras suaves. Pode assar com canela para a sobremesa." },
  { cat: "frutas", name: "Maçã", status: "ok",
    note: "Prefira madura; em crise, sem casca ou cozida/assada fica ainda mais suave." },
  { cat: "frutas", name: "Goiaba madura", status: "ok",
    note: "Bem tolerada quando madura. Evite verde (adstringente)." },
  { cat: "frutas", name: "Melancia", status: "mod",
    note: "Costuma ser tolerada, mas o volume de líquido incomoda algumas pessoas. Teste porções pequenas." },
  { cat: "frutas", name: "Manga madura", status: "mod",
    note: "Doce e suave quando bem madura. Verde é ácida — evite." },
  { cat: "frutas", name: "Abacate", status: "mod",
    note: "Gordura boa, mas gordura ainda assim. Porções pequenas (2 colheres)." },
  { cat: "frutas", name: "Uva doce (niágara, itália)", status: "mod",
    note: "Bem madura e doce costuma ser tolerada. Evite as mais azedinhas." },
  { cat: "frutas", name: "Caqui, figo, ameixa doce", status: "mod",
    note: "Frutas doces geralmente bem toleradas fora das crises." },
  { cat: "frutas", name: "Laranja, limão, tangerina, acerola", status: "no",
    note: "Cítricas: aumentam a acidez e pioram azia — principalmente em jejum e nas crises." },
  { cat: "frutas", name: "Abacaxi, maracujá, kiwi, morango", status: "no",
    note: "Ácidas para o estômago inflamado. Reintroduza só depois, com orientação." },
  { cat: "frutas", name: "Tomate (e molho de tomate)", status: "no",
    note: "É uma fruta ácida! Molhos concentrados são gatilho clássico de refluxo." },

  // ---------------- VERDURAS & LEGUMES ----------------
  { cat: "legumes", name: "Abobrinha", status: "ok",
    note: "Curinga da dieta: refogada, assada, em sopas e omeletes. Digestão facílima." },
  { cat: "legumes", name: "Chuchu", status: "ok",
    note: "Neutro e suave — perfeito para o estômago sensível." },
  { cat: "legumes", name: "Cenoura", status: "ok",
    note: "Cozida, crua ralada (fora de crise), em purês e sopas." },
  { cat: "legumes", name: "Abóbora / moranga / cabotiá", status: "ok",
    note: "Doce natural, cremosa em purês e sopas. Rica em betacaroteno, que ajuda na cicatrização." },
  { cat: "legumes", name: "Vagem", status: "ok",
    note: "Cozida no vapor fica leve e mantém os nutrientes." },
  { cat: "legumes", name: "Beterraba cozida", status: "ok",
    note: "Suave e nutritiva. Cozida ou assada." },
  { cat: "legumes", name: "Espinafre e couve refogados", status: "ok",
    note: "Refogue rapidamente com um fio de azeite. Fontes de ferro e folato." },
  { cat: "legumes", name: "Alface", status: "ok",
    note: "Folha mais leve para saladas. Higienize bem." },
  { cat: "legumes", name: "Berinjela e quiabo cozidos", status: "ok",
    note: "Bem cozidos são suaves. Evite berinjela frita ou empanada." },
  { cat: "legumes", name: "Brócolis e couve-flor cozidos", status: "mod",
    note: "Saudáveis, mas podem dar gases e estufamento. Cozinhe bem e teste porções pequenas." },
  { cat: "legumes", name: "Repolho cozido", status: "mod",
    note: "Mesmo caso: bem cozido e em pouca quantidade para não fermentar." },
  { cat: "legumes", name: "Pepino sem casca", status: "mod",
    note: "Algumas pessoas digerem mal. Sem casca e sem sementes é mais leve." },
  { cat: "legumes", name: "Cebola e alho cozidos/refogados", status: "mod",
    note: "Refogados e em pequena quantidade costumam ser tolerados." },
  { cat: "legumes", name: "Cebola e alho crus", status: "no",
    note: "Crus são irritantes e gatilho comum de azia." },
  { cat: "legumes", name: "Pimentão", status: "no",
    note: "Digestão difícil e queixa clássica de quem tem gastrite." },

  // ---------------- RAÍZES & TUBÉRCULOS ----------------
  { cat: "raizes", name: "Aipim / mandioca / macaxeira", status: "ok",
    note: "Cozida é energia leve e sem glúten. Rende purê, escondidinho e até 'cuscuz' de raiz." },
  { cat: "raizes", name: "Inhame", status: "ok",
    note: "Cremoso e suave, protege a mucosa. Cozido, em purê ou engrossando sopas." },
  { cat: "raizes", name: "Cará", status: "ok",
    note: "Primo do inhame, mesmo uso: purês, sopas e cozidos. Muito bem tolerado." },
  { cat: "raizes", name: "Batata-doce", status: "ok",
    note: "Assada ou cozida. Energia de digestão tranquila — ótima no pós-treino também." },
  { cat: "raizes", name: "Batata inglesa", status: "ok",
    note: "Cozida, assada ou em purê (com leite desnatado). Nunca frita." },
  { cat: "raizes", name: "Mandioquinha (batata-baroa)", status: "ok",
    note: "A rainha dos purês e sopas cremosas. Suave e nutritiva." },

  // ---------------- GRÃOS, PÃES & CEREAIS ----------------
  { cat: "graos", name: "Arroz branco", status: "ok",
    note: "Base segura de qualquer refeição. Bem cozido e soltinho." },
  { cat: "graos", name: "Aveia", status: "ok",
    note: "Mingau, overnight oats, panquecas. As fibras solúveis acalmam o estômago." },
  { cat: "graos", name: "Cuscuz de milho (nordestino)", status: "ok",
    note: "Leve, sem glúten e versátil: com ovo mexido, queijo branco ou frango desfiado." },
  { cat: "graos", name: "Tapioca", status: "ok",
    note: "Recheios leves: queijo minas, ricota, banana. Evite recheios gordurosos." },
  { cat: "graos", name: "Pão de forma simples / pão francês", status: "ok",
    note: "Tolerado pela maioria. Se sentir peso, tire o miolo ou toste levemente." },
  { cat: "graos", name: "Macarrão com molhos leves", status: "ok",
    note: "Com azeite e legumes, ou molho de abóbora/cenoura no lugar do tomate." },
  { cat: "graos", name: "Arroz integral e quinoa", status: "mod",
    note: "Ótimos fora das crises. Em crise, o excesso de fibra pode incomodar — volte ao branco." },
  { cat: "graos", name: "Feijão, lentilha, grão-de-bico", status: "mod",
    note: "Comece pelo caldo e porções pequenas. Deixe de molho antes de cozinhar para reduzir gases." },
  { cat: "graos", name: "Granolas açucaradas e biscoitos recheados", status: "no",
    note: "Açúcar + gordura escondida. Prefira aveia com fruta." },

  // ---------------- LATICÍNIOS ----------------
  { cat: "laticinios", name: "Iogurte natural desnatado", status: "ok",
    note: "Probióticos ajudam a flora e a digestão. Sem açúcar; adoce com fruta." },
  { cat: "laticinios", name: "Queijo minas frescal, ricota, cottage", status: "ok",
    note: "Queijos brancos e magros — os únicos liberados de verdade." },
  { cat: "laticinios", name: "Leite desnatado", status: "mod",
    note: "Alivia na hora, mas pode causar 'efeito rebote' de acidez. Pequenas quantidades." },
  { cat: "laticinios", name: "Queijos amarelos (mussarela, prato, parmesão)", status: "mod",
    note: "Gordurosos. Uma fatia fina esporádica, fora das crises." },
  { cat: "laticinios", name: "Leite integral, creme de leite, requeijão", status: "no",
    note: "Gordura láctea piora refluxo e retarda a digestão." },

  // ---------------- CHÁS & ERVAS ----------------
  { cat: "chas", name: "Espinheira-santa", status: "ok",
    note: "A erva clássica para gastrite e azia, reconhecida como fitoterápico no Brasil. Preparo: 1 col. (sopa) de folhas para 1 xícara de água quente, abafe 10 min. Tome 2–3x ao dia, de preferência 30 min antes das refeições. ⚠️ Contraindicada para gestantes e lactantes.", featured: true },
  { cat: "chas", name: "Camomila", status: "ok",
    note: "Calmante e anti-inflamatória suave — ótima à noite e nos dias de 'gastrite nervosa'." },
  { cat: "chas", name: "Erva-doce (funcho)", status: "ok",
    note: "Digestiva e boa contra gases e estufamento. Pode misturar com camomila." },
  { cat: "chas", name: "Melissa (erva-cidreira)", status: "ok",
    note: "Acalma o estômago e a ansiedade. Boa para a ceia, 1h antes de dormir." },
  { cat: "chas", name: "Gengibre", status: "mod",
    note: "Excelente contra náusea, mas em excesso pode arder. Faça chá fraco (2–3 rodelas finas) e observe." },
  { cat: "chas", name: "Boldo", status: "mod",
    note: "Digestivo amargo tradicional. Uso pontual após refeições pesadas; evite na gestação." },
  { cat: "chas", name: "Alcaçuz", status: "mod",
    note: "Usado para proteger a mucosa. Cuidado se você tem pressão alta — converse com o médico." },
  { cat: "chas", name: "Babosa (aloe vera)", status: "care",
    note: "Usada popularmente para gastrite, MAS o preparo caseiro é arriscado: a casca e o látex amarelo são tóxicos e laxativos. A Anvisa não recomenda ingerir babosa preparada em casa. Se quiser usar, escolha somente produtos de gel de aloe próprios para consumo oral, com registro, e SEMPRE com aval do seu médico.", featured: true },
  { cat: "chas", name: "Hortelã-pimenta", status: "no",
    note: "Surpresa: hortelã relaxa a válvula do esôfago e PIORA o refluxo. Evite chá e balas de menta." },
  { cat: "chas", name: "Chá preto, verde, branco e mate", status: "no",
    note: "Todos têm cafeína, que estimula a acidez. Troque pelos chás calmantes acima." },

  // ---------------- BEBIDAS ----------------
  { cat: "bebidas", name: "Água", status: "ok",
    note: "Em pequenos goles ao longo do dia. Evite volumes grandes junto com as refeições." },
  { cat: "bebidas", name: "Água de coco", status: "ok",
    note: "Hidratante e suave. Boa opção entre as refeições." },
  { cat: "bebidas", name: "Suco de melão, pera ou mamão (natural)", status: "ok",
    note: "Sucos de frutas não ácidas, sem açúcar, coados se estiver em crise." },
  { cat: "bebidas", name: "Café", status: "no",
    note: "Cafeína aumenta a acidez e relaxa a válvula do esôfago. É dos gatilhos mais fortes — inclusive o descafeinado incomoda algumas pessoas." },
  { cat: "bebidas", name: "Refrigerante e água com gás", status: "no",
    note: "O gás distende o estômago e empurra o ácido para cima." },
  { cat: "bebidas", name: "Álcool (cerveja, vinho, destilados)", status: "no",
    note: "Irrita a mucosa diretamente e piora o refluxo. Evite durante o tratamento." },
  { cat: "bebidas", name: "Sucos cítricos e energéticos", status: "no",
    note: "Acidez + cafeína. Fuja durante a recuperação." },

  // ---------------- TEMPEROS ----------------
  { cat: "temperos", name: "Ervas frescas (salsinha, cebolinha, coentro, manjericão)", status: "ok",
    note: "Dão sabor sem agredir. Use à vontade." },
  { cat: "temperos", name: "Ervas secas (alecrim, tomilho, louro, orégano)", status: "ok",
    note: "Aromáticas e seguras em quantidades normais de tempero." },
  { cat: "temperos", name: "Cúrcuma (açafrão-da-terra)", status: "ok",
    note: "Anti-inflamatória natural. Colore e tempera arroz, frango e sopas." },
  { cat: "temperos", name: "Azeite de oliva extravirgem", status: "mod",
    note: "Gordura boa, mas gordura: use 1 fio para finalizar, não para fritar." },
  { cat: "temperos", name: "Sal", status: "mod",
    note: "Com parcimônia. Excesso de sal também agride a mucosa." },
  { cat: "temperos", name: "Pimentas (do reino, malagueta, dedo-de-moça)", status: "no",
    note: "Irritação direta na mucosa inflamada. Corte durante o tratamento." },
  { cat: "temperos", name: "Molhos prontos (ketchup, mostarda, shoyu, inglês) e caldos em cubo", status: "no",
    note: "Ácidos, salgados e cheios de aditivos. Tempere com ervas de verdade." },
  { cat: "temperos", name: "Vinagre", status: "no",
    note: "Ácido puro na salada. Troque por um fio de azeite com ervas." },

  // ---------------- DOCES ----------------
  { cat: "doces", name: "Frutas assadas (banana ou maçã com canela suave)", status: "ok",
    note: "A sobremesa oficial da recuperação: doce natural, quentinha e leve." },
  { cat: "doces", name: "Gelatina", status: "ok",
    note: "Leve e refrescante. Prefira as versões com menos corante." },
  { cat: "doces", name: "Mel", status: "mod",
    note: "1 colher de chá para adoçar chás ou iogurte. Tem ação suavizante, mas é açúcar." },
  { cat: "doces", name: "Doce caseiro de banana/mamão (pouco açúcar)", status: "mod",
    note: "Feito em casa, sem excesso de açúcar, em porção pequena." },
  { cat: "doces", name: "Chocolate", status: "no",
    note: "Cafeína + gordura + relaxa a válvula do esôfago. Um dos gatilhos mais traiçoeiros." },
  { cat: "doces", name: "Sobremesas cremosas e gordurosas (tortas, sorvetes, brigadeiro)", status: "no",
    note: "Gordura + açúcar em dose alta. Deixe para depois da recuperação, com moderação." },

  /* ---------------- AMPLIAÇÃO DO GUIA ---------------- */
  // Carnes & Peixes
  { cat: "carnes", name: "Peito de peru fresco assado", status: "ok",
    note: "O peru de verdade (assado em casa) é magro e leve — bem diferente do 'peito de peru' fatiado de pacote, que é embutido." },
  { cat: "carnes", name: "Atum fresco ou enlatado em água", status: "mod",
    note: "Proteína magra. Prefira o enlatado em ÁGUA (o em óleo pesa). Fresco, grelhe levemente." },
  { cat: "carnes", name: "Bacalhau dessalgado", status: "mod",
    note: "Peixe magro, porém muito salgado — dessalgue bem (24–48h trocando a água) e prepare cozido ou assado." },
  { cat: "carnes", name: "Camarão cozido ou grelhado", status: "mod",
    note: "Pouca gordura quando não é frito nem à milanesa. Porções pequenas, sem molhos pesados." },
  { cat: "carnes", name: "Nuggets, frango empanado e salgadinhos de festa", status: "no",
    note: "Empanados industriais = fritura + gordura escondida + aditivos. Gatilho quase garantido." },

  // Ovos
  { cat: "ovos", name: "Ovos de codorna cozidos", status: "ok",
    note: "Miniaturas bem-vindas em saladas e lanches. Sempre cozidos." },
  { cat: "ovos", name: "Ovo cru (gemada, maionese caseira)", status: "no",
    note: "Além do risco de salmonela, é indigesto. Ovo, só bem cozido." },

  // Frutas
  { cat: "frutas", name: "Banana-da-terra cozida ou assada", status: "ok",
    note: "Vira acompanhamento quentinho e doce natural — assada com canela suave é sobremesa." },
  { cat: "frutas", name: "Fruta-do-conde (pinha, ata)", status: "ok",
    note: "Doce e macia, bem tolerada quando madura." },
  { cat: "frutas", name: "Pitaya", status: "ok",
    note: "Suave, pouco ácida e rica em fibras leves." },
  { cat: "frutas", name: "Pêssego e nectarina maduros", status: "mod",
    note: "Maduros e doces costumam ser tolerados; azedinhos, não. Teste fora das crises." },
  { cat: "frutas", name: "Graviola", status: "mod",
    note: "Levemente ácida. Em vitamina com banana fica mais suave." },
  { cat: "frutas", name: "Jaca madura", status: "mod",
    note: "Doce, mas fermenta em excesso — porção pequena para evitar gases." },
  { cat: "frutas", name: "Frutas secas (damasco, uva-passa, ameixa seca)", status: "mod",
    note: "Concentradas em açúcar; punhado pequeno. Ameixa seca ajuda o intestino." },
  { cat: "frutas", name: "Açaí puro batido com banana", status: "mod",
    note: "O açaí em si é neutro; o problema é o xarope. Peça SEM xarope de guaraná e sem coberturas gordurosas." },
  { cat: "frutas", name: "Açaí com xarope de guaraná e coberturas", status: "no",
    note: "Xarope de guaraná tem cafeína e muito açúcar; as coberturas somam gordura." },

  // Verduras & Legumes
  { cat: "legumes", name: "Acelga cozida", status: "ok",
    note: "Refogada rapidinho ou no vapor, é leve e suave." },
  { cat: "legumes", name: "Escarola refogada", status: "ok",
    note: "O amargor suave estimula a digestão. Refogue com um fio de azeite." },
  { cat: "legumes", name: "Aspargos cozidos", status: "ok",
    note: "Leves e elegantes — no vapor ou grelhados rapidamente." },
  { cat: "legumes", name: "Aipo (salsão)", status: "ok",
    note: "Cru em palitos (fora de crise) ou cozido em sopas e caldos." },
  { cat: "legumes", name: "Maxixe", status: "ok",
    note: "Cozido ou refogado, é leve e típico do Nordeste." },
  { cat: "legumes", name: "Taioba e ora-pro-nóbis cozidas", status: "ok",
    note: "Folhas nutritivas da cozinha mineira. Sempre bem cozidas (taioba nunca crua)." },
  { cat: "legumes", name: "Alho-poró cozido", status: "mod",
    note: "Família da cebola: cozido e em pouca quantidade costuma passar bem." },
  { cat: "legumes", name: "Milho-verde", status: "mod",
    note: "A casquinha do grão é difícil de digerir. Bem cozido, mastigue muito bem." },
  { cat: "legumes", name: "Ervilha fresca", status: "mod",
    note: "Nutritiva, mas leguminosa: pode dar gases. Porções pequenas." },
  { cat: "legumes", name: "Palmito", status: "mod",
    note: "O palmito é leve, mas a salmoura da conserva é ácida. Escorra e lave bem antes de usar." },
  { cat: "legumes", name: "Jiló cozido", status: "mod",
    note: "O amargor incomoda algumas pessoas com gastrite; outras digerem bem. Teste." },
  { cat: "legumes", name: "Rabanete", status: "no",
    note: "Picante por natureza — irrita a mucosa inflamada." },
  { cat: "legumes", name: "Tomate-cereja", status: "no",
    note: "Continua sendo tomate: ácido. Vale a mesma regra do tomate comum." },

  // Grãos, Pães & Cereais
  { cat: "graos", name: "Polenta / angu de milho", status: "ok",
    note: "Milho cozido cremoso: leve, sem glúten e reconfortante. Sem queijos gordos por cima." },
  { cat: "graos", name: "Canjiquinha (quirera de milho)", status: "ok",
    note: "Clássico mineiro. Cozida com frango magro vira um jantar quentinho e digesto (receita no app!)." },
  { cat: "graos", name: "Chia hidratada", status: "ok",
    note: "Deixe de molho (vira um gel que protege). Boa no iogurte e no overnight oats." },
  { cat: "graos", name: "Linhaça moída", status: "ok",
    note: "Moída na hora, 1 colher no mingau ou na vitamina. Fibras suaves e ômega-3." },
  { cat: "graos", name: "Torradas simples", status: "ok",
    note: "Mais fáceis de digerir que pão fresco. Sem margarina — use ricota temperada." },
  { cat: "graos", name: "Pão de queijo", status: "mod",
    note: "Polvilho + queijo: 1–2 unidades pequenas, fora das crises. A versão de frigideira do app é mais leve." },
  { cat: "graos", name: "Biscoito de polvilho", status: "mod",
    note: "Leve, mas alguns são fritos ou muito gordurosos — leia o rótulo, prefira assados." },
  { cat: "graos", name: "Macarrão instantâneo (miojo)", status: "no",
    note: "Massa pré-frita + tempero ultrassalgado com glutamato. Tudo que o estômago não quer." },

  // Laticínios
  { cat: "laticinios", name: "Kefir", status: "ok",
    note: "Probiótico poderoso para a flora. Comece com meio copo e observe." },
  { cat: "laticinios", name: "Iogurte grego desnatado (sem açúcar)", status: "mod",
    note: "Mais proteico e com menos lactose. Escolha o DESNATADO — o tradicional é gorduroso." },
  { cat: "laticinios", name: "Manteiga / ghee", status: "mod",
    note: "Gordura concentrada: raspadinha fina, esporádica, fora das crises. Melhor trocar por ricota." },
  { cat: "laticinios", name: "Margarina", status: "no",
    note: "Gordura de baixa qualidade e aditivos. Não vale o espaço no pão." },

  // Chás & Ervas
  { cat: "chas", name: "Capim-limão (capim-santo)", status: "ok",
    note: "Calmante e digestivo, sabor cítrico SEM a acidez do limão. Ótimo à noite." },
  { cat: "chas", name: "Macela (marcela)", status: "ok",
    note: "Tradição do Sul para digestão e azia. Abafe 1 col. (chá) de flores por 10 min." },
  { cat: "chas", name: "Malva / alteia", status: "ok",
    note: "Ricas em mucilagem, que forma uma película protetora sobre a mucosa irritada." },
  { cat: "chas", name: "Guaçatonga", status: "mod",
    note: "Erva brasileira tradicionalmente usada para gastrite e úlcera. Use por períodos curtos e avise seu médico." },
  { cat: "chas", name: "Mulungu", status: "mod",
    note: "Calmante para a 'gastrite nervosa' e o sono. Não combine com sedativos; converse com o médico." },
  { cat: "chas", name: "Hibisco", status: "no",
    note: "Bonito, mas bem ácido — azedinho no sabor, azedo no estômago." },
  { cat: "chas", name: "Kombucha", status: "no",
    note: "Fermentado ácido E com gás: combinação ruim para refluxo, apesar da fama saudável." },

  // Bebidas
  { cat: "bebidas", name: "Cevada solúvel (substituto do café)", status: "ok",
    note: "Sabor tostado que lembra café, ZERO cafeína. O truque para matar a saudade do cafezinho." },
  { cat: "bebidas", name: "Bebida vegetal de arroz ou aveia", status: "ok",
    note: "Leves e neutras — ótimas para mingaus e vitaminas de quem não quer leite." },
  { cat: "bebidas", name: "Bebida de amêndoas", status: "mod",
    note: "Suave, mas com um pouco mais de gordura. Prefira as sem açúcar." },
  { cat: "bebidas", name: "Bebida de soja", status: "mod",
    note: "Pode causar gases em algumas pessoas. Teste porções pequenas." },
  { cat: "bebidas", name: "Café descafeinado", status: "mod",
    note: "Sem a cafeína, mas ainda com compostos que irritam alguns estômagos. Se não abre mão, 1 xícara pequena fora da crise — ou troque pela cevada." },
  { cat: "bebidas", name: "Suco de uva integral", status: "mod",
    note: "Doce e sem acidez cítrica, mas concentrado em açúcar: meio copo, diluído." },
  { cat: "bebidas", name: "Chá gelado industrializado", status: "no",
    note: "Chá preto (cafeína) + muito açúcar + acidulantes. Bem diferente do chá de verdade." },
  { cat: "bebidas", name: "Isotônicos", status: "no",
    note: "Acidulantes e corantes. Para hidratar, água e água de coco ganham fácil." },

  // Temperos
  { cat: "temperos", name: "Noz-moscada", status: "ok",
    note: "Uma raspadinha em purês e molhos brancos leves. Quantidade de tempero é segura." },
  { cat: "temperos", name: "Canela", status: "mod",
    note: "Uma pitada SUAVE perfuma frutas assadas e mingaus. Em excesso pode irritar — vá de leve." },
  { cat: "temperos", name: "Cominho", status: "mod",
    note: "Tradicional no feijão e na carne. Em pequenas doses, tranquilo para a maioria." },
  { cat: "temperos", name: "Páprica doce", status: "mod",
    note: "Cor e sabor sem ardência. Evite as versões PICANTE e DEFUMADA." },
  { cat: "temperos", name: "Curry pronto", status: "mod",
    note: "Misturas variam — muitas levam pimenta. Teste pouquinho ou monte a sua (cúrcuma + cominho + coentro)." },
  { cat: "temperos", name: "Gergelim e tahine", status: "mod",
    note: "Oleaginosas: nutritivas mas gordurosas. 1 colher de tahine no homus caseiro está de bom tamanho." },

  // Doces
  { cat: "doces", name: "Picolé caseiro de fruta permitida", status: "ok",
    note: "Melão, mamão ou banana batidos e congelados. Refresca sem agredir (receita no app!)." },
  { cat: "doces", name: "Castanhas e amendoim", status: "mod",
    note: "Gorduras boas, porém gorduras: um punhado pequeno (fechado na mão) por dia." },
  { cat: "doces", name: "Paçoca", status: "mod",
    note: "Amendoim + açúcar: 1 unidade esporádica, fora das crises." },
  { cat: "doces", name: "Arroz-doce leve", status: "mod",
    note: "Feito com leite desnatado e pouco açúcar, em porção pequena, é um afago tolerável." },
  { cat: "doces", name: "Doce de leite", status: "no",
    note: "Leite integral + açúcar concentrados. Espere a recuperação." },
];

/* =========================================================
   RECEITAS — fáceis, modernas e amigas do estômago
   ========================================================= */
const MEAL_TYPES = [
  { id: "cafe",   name: "Café da manhã", icon: "🌅" },
  { id: "almoco", name: "Almoço",        icon: "🍽️" },
  { id: "janta",  name: "Jantar",        icon: "🌙" },
  { id: "lanche", name: "Lanches & Ceia",icon: "🍎" },
];

const RECIPES = [
  // ---------- CAFÉ DA MANHÃ ----------
  { id: "crepioca", meal: "cafe", name: "Crepioca de queijo minas", time: 10, portions: 1,
    tags: ["rápida", "sem glúten", "proteica"],
    ing: ["1 ovo", "2 col. (sopa) de goma de tapioca", "1 pitada de sal", "2 fatias de queijo minas frescal", "Cebolinha picada (opcional)"],
    steps: ["Misture o ovo, a tapioca e o sal até ficar homogêneo.",
      "Despeje em frigideira antiaderente quente, em fogo baixo, sem gordura.",
      "Quando firmar as bordas (± 2 min), vire com uma espátula.",
      "Coloque o queijo, dobre ao meio e sirva com a cebolinha."],
    tip: "Versão doce: recheie com banana amassada e um toque de canela suave." },

  { id: "cuscuz-ovo", meal: "cafe", name: "Cuscuz nordestino com ovo mexido cremoso", time: 15, portions: 2,
    tags: ["sem glúten", "clássica", "barata"],
    ing: ["1 xícara de flocão de milho", "1/2 xícara de água", "Sal a gosto", "2 ovos", "1 col. (sopa) de leite desnatado", "1 fio de azeite"],
    steps: ["Hidrate o flocão com a água e o sal por 10 min.",
      "Cozinhe na cuscuzeira (ou no micro-ondas, 3 min em pote furado) até firmar.",
      "Bata os ovos com o leite. Cozinhe em fogo BAIXO na antiaderente, mexendo sempre, até ficar cremoso.",
      "Sirva o ovo sobre o cuscuz com um fio de azeite."],
    tip: "Fogo baixo é o segredo do ovo cremoso sem precisar de manteiga." },

  { id: "overnight", meal: "cafe", name: "Overnight oats de banana e mamão", time: 5, portions: 1,
    tags: ["rápida", "sem cozinhar", "moderna"],
    ing: ["4 col. (sopa) de aveia em flocos", "150 ml de leite desnatado ou bebida vegetal de arroz", "1/2 banana madura amassada", "2 col. de mamão picado", "1 col. (chá) de mel (opcional)"],
    steps: ["Num pote com tampa, misture a aveia, o leite e a banana amassada.",
      "Feche e deixe na geladeira de um dia para o outro (ou 30 min, se tiver pressa).",
      "Na hora de comer, cubra com o mamão e o mel."],
    tip: "Prepare 2–3 potes de uma vez: café da manhã pronto para os próximos dias." },

  { id: "panqueca-banana", meal: "cafe", name: "Panqueca de banana e aveia (3 ingredientes)", time: 12, portions: 1,
    tags: ["rápida", "sem açúcar", "moderna"],
    ing: ["1 banana madura", "1 ovo", "3 col. (sopa) de aveia em flocos finos", "Canela suave (opcional)"],
    steps: ["Amasse bem a banana e misture com o ovo e a aveia.",
      "Despeje pequenas porções na frigideira antiaderente, fogo baixo.",
      "Doure 2 min de cada lado, virando com cuidado.",
      "Finalize com uma pitada leve de canela."],
    tip: "Quanto mais madura a banana, mais doce a panqueca — sem precisar de açúcar." },

  { id: "mingau-maca", meal: "cafe", name: "Mingau de aveia com maçã cozida", time: 15, portions: 1,
    tags: ["conforto", "para crises"],
    ing: ["3 col. (sopa) de aveia", "200 ml de leite desnatado ou água", "1/2 maçã sem casca em cubinhos", "1 col. (chá) de mel", "Canela suave"],
    steps: ["Cozinhe a maçã com 2 col. de água até amolecer (± 5 min).",
      "Junte a aveia e o leite; mexa em fogo baixo até engrossar.",
      "Adoce com o mel e polvilhe canela de leve."],
    tip: "Receita coringa para os dias de crise: morna, macia e calmante." },

  { id: "tapioca-ricota", meal: "cafe", name: "Tapioca de ricota temperada com cenoura", time: 10, portions: 1,
    tags: ["rápida", "sem glúten"],
    ing: ["3 col. (sopa) de goma de tapioca", "3 col. (sopa) de ricota amassada", "2 col. de cenoura ralada fina", "Salsinha e sal a gosto"],
    steps: ["Misture a ricota com a cenoura, a salsinha e o sal.",
      "Espalhe a goma na frigideira quente e aguarde firmar (± 2 min).",
      "Recheie, dobre e sirva."],
    tip: "A cenoura ralada dá crocância suave sem pesar." },

  { id: "vitamina-mamao", meal: "cafe", name: "Vitamina de mamão com aveia", time: 5, portions: 1,
    tags: ["rápida", "líquida", "para crises"],
    ing: ["1 fatia grossa de mamão", "150 ml de leite desnatado ou bebida de arroz", "1 col. (sopa) de aveia", "Gelo (opcional)"],
    steps: ["Bata tudo no liquidificador até ficar cremoso.", "Sirva em seguida."],
    tip: "Nos dias em que mastigar incomoda, uma vitamina resolve o café da manhã." },

  // ---------- ALMOÇO ----------
  { id: "frango-inhame", meal: "almoco", name: "Frango grelhado com purê de inhame", time: 35, portions: 2,
    tags: ["clássica", "proteica"],
    ing: ["2 filés de frango", "Sal, cúrcuma e ervas (tomilho ou orégano)", "4 inhames médios", "1 fio de azeite", "Salsinha"],
    steps: ["Cozinhe os inhames descascados até ficarem macios (± 15 min); amasse com sal e um fio de azeite.",
      "Tempere o frango com sal, cúrcuma e as ervas.",
      "Grelhe na antiaderente em fogo médio, 4–5 min por lado, sem deixar queimar.",
      "Sirva sobre o purê com salsinha por cima."],
    tip: "O purê de inhame é cremoso naturalmente — não precisa de manteiga nem creme." },

  { id: "papelote", meal: "almoco", name: "Peixe em papelote com legumes", time: 30, portions: 2,
    tags: ["forno", "leve", "moderna"],
    ing: ["2 filés de tilápia ou merluza", "1 abobrinha em rodelas", "1 cenoura em tiras finas", "Sal, ervas finas e 1 fio de azeite", "Papel-manteiga ou alumínio"],
    steps: ["Corte 2 folhas grandes de papel. No centro de cada uma, faça uma cama de legumes.",
      "Coloque o filé por cima, tempere e regue com o azeite.",
      "Feche bem os pacotinhos e asse a 200 °C por 20 min.",
      "Abra o papelote no prato — o vapor perfumado é o show."],
    tip: "Técnica de restaurante, zero fritura e quase nenhuma louça." },

  { id: "escondidinho", meal: "almoco", name: "Escondidinho de aipim com frango", time: 45, portions: 4,
    tags: ["conforto", "para a família", "sem glúten"],
    ing: ["500 g de aipim (mandioca) cozido", "300 g de frango cozido e desfiado", "1/2 cebola picada refogada", "Cenoura ralada", "Salsinha, sal e cúrcuma", "2 col. de ricota ou queijo minas para gratinar"],
    steps: ["Amasse o aipim ainda quente com um pouco da água do cozimento até virar purê.",
      "Refogue a cebola no fio de azeite, junte o frango, a cenoura, a cúrcuma e a salsinha.",
      "Monte em um refratário: frango embaixo, purê por cima, queijo esfarelado no topo.",
      "Leve ao forno a 200 °C por 15 min para gratinar de leve."],
    tip: "Rende marmitas ótimas — congele em porções individuais." },

  { id: "airfryer-frango", meal: "almoco", name: "Frango na airfryer com batata-doce", time: 30, portions: 2,
    tags: ["airfryer", "moderna", "sem fritura"],
    ing: ["2 sobrecoxas sem pele ou filés", "1 batata-doce grande em cubos", "Sal, alecrim e cúrcuma", "1 fio de azeite"],
    steps: ["Tempere o frango e a batata-doce com sal, alecrim, cúrcuma e o fio de azeite.",
      "Airfryer a 180 °C: batata-doce por 20 min, chacoalhando na metade.",
      "Frango por 18–20 min, virando na metade, até dourar.",
      "Sirva com salada de alface e cenoura."],
    tip: "A airfryer dá a crocância da fritura sem o óleo que provoca a azia." },

  { id: "bowl-frango", meal: "almoco", name: "Bowl de arroz, frango desfiado e legumes", time: 25, portions: 2,
    tags: ["moderna", "marmita", "equilibrada"],
    ing: ["1 xícara de arroz cozido", "1 xícara de frango desfiado", "1/2 abobrinha em cubinhos refogada", "1/2 cenoura ralada", "Folhas de alface", "Azeite, sal e cebolinha"],
    steps: ["Monte o bowl em camadas: arroz na base, frango, abobrinha e cenoura em setores.",
      "Complete com as folhas, o fio de azeite e a cebolinha.",
      "Misture na hora de comer."],
    tip: "Fórmula do bowl perfeito: 1 base + 1 proteína + 2 legumes + 1 folha." },

  { id: "carne-mandioquinha", meal: "almoco", name: "Carne magra cozida com mandioquinha", time: 50, portions: 4,
    tags: ["panela de pressão", "conforto"],
    ing: ["500 g de músculo ou patinho em cubos", "3 mandioquinhas em pedaços", "1 cenoura em rodelas", "1/2 cebola, sal, louro e salsinha"],
    steps: ["Doure levemente a carne na própria panela de pressão com um fio de azeite.",
      "Junte a cebola, cubra com água, adicione o louro e cozinhe na pressão por 25 min.",
      "Abra, acrescente a mandioquinha e a cenoura e cozinhe mais 10 min sem pressão.",
      "Acerte o sal e finalize com salsinha. O caldo engrossa naturalmente."],
    tip: "Carne bem cozida e desmanchando é muito mais fácil de digerir do que grelhados malpassados." },

  { id: "risoto-abobora", meal: "almoco", name: "Risoto leve de abóbora (sem vinho)", time: 40, portions: 3,
    tags: ["moderna", "sem vinho", "conforto"],
    ing: ["1 xícara de arroz arbóreo (ou branco comum)", "2 xícaras de abóbora em cubos", "1 litro de caldo caseiro de legumes (sem cubo!)", "1/2 cebola picada", "2 col. de ricota", "Sal e salsinha"],
    steps: ["Cozinhe a abóbora no caldo até amolecer; amasse metade dela no próprio caldo.",
      "Refogue a cebola no fio de azeite, junte o arroz e vá adicionando o caldo aos poucos, mexendo.",
      "Quando o arroz estiver al dente (± 18 min), junte os cubos restantes de abóbora.",
      "Finalize com a ricota e a salsinha — cremosidade sem creme de leite."],
    tip: "O vinho do risoto tradicional é ácido — o caldo caseiro substitui sem dó." },

  // ---------- JANTAR ----------
  { id: "sopa-abobora", meal: "janta", name: "Sopa creme de abóbora com gengibre suave", time: 30, portions: 3,
    tags: ["leve", "para crises", "conforto"],
    ing: ["500 g de abóbora cabotiá em cubos", "1 rodela fina de gengibre", "1/2 cebola", "600 ml de água", "Sal e cebolinha"],
    steps: ["Refogue a cebola no fio de azeite, junte a abóbora, o gengibre e a água.",
      "Cozinhe 15–20 min até a abóbora desmanchar.",
      "Bata no liquidificador (retire o gengibre se preferir mais suave).",
      "Sirva com cebolinha picada."],
    tip: "Jantar líquido e morno é o melhor amigo de quem tem refluxo noturno." },

  { id: "canja", meal: "janta", name: "Canja de galinha clássica", time: 40, portions: 4,
    tags: ["clássica", "para crises", "conforto"],
    ing: ["1 peito de frango", "1/2 xícara de arroz", "1 cenoura em cubinhos", "1 batata em cubos", "1/2 cebola, sal, louro e salsinha", "1,5 litro de água"],
    steps: ["Cozinhe o frango com a cebola, o louro e a água por 20 min; retire e desfie.",
      "No mesmo caldo, cozinhe o arroz, a cenoura e a batata por 15 min.",
      "Volte o frango desfiado, acerte o sal e finalize com salsinha."],
    tip: "A receita da vovó é oficialmente aprovada pela gastroenterologia." },

  { id: "omelete-forno", meal: "janta", name: "Omelete de forno com legumes", time: 30, portions: 2,
    tags: ["forno", "proteica", "aproveitamento"],
    ing: ["4 ovos", "1/2 abobrinha ralada", "1/2 cenoura ralada", "2 col. de ricota", "Sal, orégano e salsinha"],
    steps: ["Bata os ovos com o sal e o orégano.",
      "Misture os legumes ralados e a ricota esfarelada.",
      "Despeje em forma untada com fio de azeite e asse a 180 °C por 20 min, até firmar e dourar de leve."],
    tip: "Aceita qualquer legume permitido que sobrou na geladeira." },

  { id: "pure-cara", meal: "janta", name: "Purê de cará com frango dourado", time: 30, portions: 2,
    tags: ["raízes", "conforto"],
    ing: ["3 carás médios", "1 xícara de frango desfiado", "Sal, cúrcuma e cebolinha", "1 fio de azeite"],
    steps: ["Cozinhe o cará descascado até amolecer e amasse com sal (use água do cozimento para dar cremosidade).",
      "Na antiaderente, doure o frango desfiado com o fio de azeite e a cúrcuma até ficar levemente crocante.",
      "Sirva o frango por cima do purê, com cebolinha."],
    tip: "Cará e inhame são intercambiáveis — use o que achar na feira." },

  { id: "sopa-legumes", meal: "janta", name: "Sopa de legumes com músculo desfiado", time: 50, portions: 4,
    tags: ["panela de pressão", "completa"],
    ing: ["300 g de músculo", "1 batata, 1 cenoura, 1 chuchu e 1 pedaço de abóbora em cubos", "1/2 cebola, sal e louro", "Salsinha"],
    steps: ["Cozinhe o músculo na pressão com a cebola, o louro e água por 30 min; desfie.",
      "No caldo, cozinhe os legumes por 10–15 min.",
      "Volte a carne desfiada, acerte o sal e sirva com salsinha."],
    tip: "Congele em potes individuais: jantar pronto para a semana inteira." },

  { id: "tilapia-pure", meal: "janta", name: "Tilápia grelhada com purê de mandioquinha", time: 30, portions: 2,
    tags: ["leve", "rápida"],
    ing: ["2 filés de tilápia", "3 mandioquinhas", "Sal, ervas finas e 1 fio de azeite", "Salsinha"],
    steps: ["Cozinhe a mandioquinha e amasse com sal até virar um purê sedoso.",
      "Tempere os filés e grelhe na antiaderente 3 min por lado, com cuidado para não desmanchar.",
      "Monte o prato e finalize com salsinha e o fio de azeite."],
    tip: "Peixe branco à noite = digestão tranquila antes de dormir." },

  // ---------- LANCHES & CEIA ----------
  { id: "banana-aveia", meal: "lanche", name: "Banana amassada com aveia e canela", time: 3, portions: 1,
    tags: ["rápida", "3 ingredientes"],
    ing: ["1 banana madura", "1 col. (sopa) de aveia", "Canela suave"],
    steps: ["Amasse a banana, misture a aveia e polvilhe a canela.", "Pronto. Sério."],
    tip: "O lanche de 3 minutos que salva a fome da tarde sem apelar para besteira." },

  { id: "iogurte-mamao", meal: "lanche", name: "Iogurte natural com mamão e mel", time: 5, portions: 1,
    tags: ["rápida", "probiótica"],
    ing: ["1 pote de iogurte natural desnatado", "2 col. de mamão em cubos", "1 col. (chá) de mel", "1 col. de aveia (opcional)"],
    steps: ["Monte em camadas num copo: iogurte, mamão, mel e aveia.", "Sirva gelado."],
    tip: "Probióticos do iogurte + papaína do mamão = dupla digestiva." },

  { id: "maca-airfryer", meal: "lanche", name: "Maçã assada na airfryer com canela", time: 15, portions: 1,
    tags: ["airfryer", "sobremesa saudável"],
    ing: ["1 maçã", "1 col. (chá) de mel", "Canela suave", "1 col. de aveia (opcional)"],
    steps: ["Corte a maçã ao meio e retire as sementes.",
      "Regue com o mel e polvilhe a canela.",
      "Airfryer a 160 °C por 12 min, até ficar macia e perfumada."],
    tip: "Mata a vontade de doce sem chocolate e sem culpa." },

  { id: "gelatina-frutas", meal: "lanche", name: "Gelatina com frutas permitidas", time: 10, portions: 4,
    tags: ["geladeira", "leve"],
    ing: ["1 pacote de gelatina (sabor suave, ex.: pêssego)", "1 banana em rodelas", "2 col. de mamão em cubos"],
    steps: ["Prepare a gelatina conforme a embalagem.",
      "Distribua as frutas em potinhos e despeje a gelatina morna por cima.",
      "Geladeira por 3 horas."],
    tip: "Sobremesa gelada segura para depois do almoço de domingo." },

  { id: "cha-espinheira", meal: "lanche", name: "Chá de espinheira-santa (preparo correto)", time: 15, portions: 1,
    tags: ["chá terapêutico", "fitoterápico"],
    ing: ["1 col. (sopa) de folhas secas de espinheira-santa", "1 xícara (200 ml) de água filtrada"],
    steps: ["Ferva a água e desligue o fogo.",
      "Adicione as folhas, tampe e abafe por 10 minutos.",
      "Coe e tome morno, de preferência 30 min antes das refeições.",
      "Use 2–3 xícaras ao dia, por períodos de até 4 semanas, com acompanhamento."],
    tip: "⚠️ Contraindicado para gestantes e lactantes. Converse com seu médico antes de usar diariamente." },

  /* ---------- AMPLIAÇÃO: CAFÉ DA MANHÃ ---------- */
  { id: "pao-queijo-frigideira", meal: "cafe", name: "Pão de queijo de frigideira (leve)", time: 10, portions: 1,
    tags: ["rápida", "sem glúten", "moderna"],
    ing: ["1 ovo", "2 col. (sopa) de polvilho doce", "2 col. (sopa) de queijo minas ou ricota amassada", "1 col. (sopa) de leite desnatado", "1 pitada de sal"],
    steps: ["Misture tudo até virar uma massinha cremosa.",
      "Despeje na frigideira antiaderente, fogo baixo, e tampe por 3 min.",
      "Vire e doure mais 2 min. Fica com cara de pão de queijo gigante, sem fritura."],
    tip: "Mata a vontade de pão de queijo com muito menos gordura que o assado tradicional." },

  { id: "smoothie-verde", meal: "cafe", name: "Smoothie verde suave", time: 5, portions: 1,
    tags: ["rápida", "líquida", "moderna"],
    ing: ["1 folha de couve sem o talo", "1 banana madura", "200 ml de água de coco", "1 col. (chá) de mel (opcional)"],
    steps: ["Bata tudo no liquidificador até ficar bem liso.", "Sirva na hora, sem coar para aproveitar as fibras."],
    tip: "A banana e a água de coco deixam a couve suave — verde que não agride." },

  { id: "crepioca-doce", meal: "cafe", name: "Crepioca doce de banana", time: 10, portions: 1,
    tags: ["rápida", "sem glúten", "sem açúcar"],
    ing: ["1 ovo", "2 col. (sopa) de goma de tapioca", "1/2 banana madura em rodelas", "Canela suave"],
    steps: ["Misture o ovo e a goma; despeje na frigideira antiaderente em fogo baixo.",
      "Quando firmar, disponha as rodelas de banana em metade, polvilhe a canela e dobre.",
      "Aqueça mais 1 min para a banana amaciar."],
    tip: "A banana bem madura carameliza sozinha com o calor — doce sem açúcar." },

  { id: "muffin-banana", meal: "cafe", name: "Muffins de banana e aveia (de forno)", time: 30, portions: 6,
    tags: ["forno", "para a semana", "sem açúcar"],
    ing: ["2 bananas maduras amassadas", "2 ovos", "1 xícara de aveia em flocos", "1 col. (chá) de fermento em pó", "Canela suave"],
    steps: ["Misture as bananas, os ovos e a aveia; por último o fermento.",
      "Distribua em 6 forminhas (de silicone ou untadas com fio de azeite).",
      "Asse a 180 °C por 20–25 min, até dourar."],
    tip: "Faça no domingo: café da manhã e lanche prontos para vários dias." },

  { id: "congee", meal: "cafe", name: "Arroz cremoso de crise (congee)", time: 30, portions: 2,
    tags: ["para crises", "conforto"],
    ing: ["1/2 xícara de arroz branco", "4 xícaras de água", "1 rodela fina de gengibre (opcional)", "Sal", "Cebolinha e frango desfiado para servir (opcional)"],
    steps: ["Cozinhe o arroz na água com o gengibre, em fogo baixo, mexendo às vezes, por 25–30 min, até virar um mingau cremoso.",
      "Acerte o sal e retire o gengibre.",
      "Sirva puro ou com frango desfiado e cebolinha."],
    tip: "É o 'mingau de arroz' asiático: nos piores dias de crise, é a refeição mais gentil que existe." },

  { id: "iogurte-crocante", meal: "cafe", name: "Iogurte com farofinha de aveia tostada", time: 15, portions: 2,
    tags: ["rápida", "probiótica", "crocante"],
    ing: ["2 potes de iogurte natural desnatado", "6 col. (sopa) de aveia em flocos", "1 col. (sopa) de mel", "Canela suave", "Banana ou mamão picado"],
    steps: ["Toste a aveia na frigideira seca, mexendo, até cheirar bem (± 4 min); junte o mel e a canela e desligue.",
      "Deixe esfriar — vira uma 'granola' simples sem fritura.",
      "Monte: iogurte, fruta e a farofinha por cima."],
    tip: "A crocância que a granola industrial prometia, sem o açúcar e a gordura dela." },

  { id: "omelete-claras", meal: "cafe", name: "Omelete de claras com queijo branco", time: 10, portions: 1,
    tags: ["rápida", "proteica", "levíssima"],
    ing: ["3 claras (ou 2 claras + 1 ovo)", "2 col. de queijo minas esfarelado", "Cebolinha, sal e orégano"],
    steps: ["Bata as claras com o sal e o orégano até espumar de leve.",
      "Despeje na antiaderente em fogo baixo; espalhe o queijo e a cebolinha.",
      "Dobre quando firmar. Mais leve, impossível."],
    tip: "Sobra gema? Cozinhe e use no patê de frango do app." },

  /* ---------- AMPLIAÇÃO: ALMOÇO ---------- */
  { id: "almondegas-frango", meal: "almoco", name: "Almôndegas de frango assadas com purê", time: 40, portions: 3,
    tags: ["forno", "para a família", "marmita"],
    ing: ["400 g de frango moído (ou peito triturado)", "3 col. (sopa) de aveia em flocos finos", "1 ovo", "Salsinha, sal e cúrcuma", "4 batatas para o purê", "1 col. de ricota"],
    steps: ["Misture o frango, a aveia, o ovo e os temperos; modele bolinhas.",
      "Asse a 200 °C por 20–25 min (ou airfryer 180 °C, 15 min), virando na metade.",
      "Cozinhe as batatas e amasse com a ricota e sal.",
      "Sirva as almôndegas sobre o purê, com salsinha."],
    tip: "Sem molho de tomate: um fio de azeite e ervas resolvem. Congele as almôndegas cruas para a semana." },

  { id: "macarrao-abobora", meal: "almoco", name: "Macarrão ao molho de abóbora (o 'fake tomate')", time: 30, portions: 3,
    tags: ["moderna", "sem tomate", "truque"],
    ing: ["250 g de macarrão", "2 xícaras de abóbora cozida", "1/2 xícara do caldo do cozimento", "1/2 cebola refogada", "1 col. de ricota", "Sal, manjericão e um fio de azeite"],
    steps: ["Bata a abóbora com o caldo, a cebola e o sal — vira um 'molho vermelho' cremoso.",
      "Cozinhe o macarrão al dente.",
      "Misture o molho ao macarrão, finalize com ricota, manjericão e azeite."],
    tip: "Visual e conforto de molho de tomate, zero acidez. Guarde essa carta na manga." },

  { id: "strogonoff-leve", meal: "almoco", name: "Strogonoff leve de frango", time: 30, portions: 3,
    tags: ["clássica adaptada", "sem ketchup"],
    ing: ["400 g de frango em tiras", "1/2 cebola picada", "1 xícara de iogurte natural desnatado", "1 col. (chá) de cúrcuma", "Sal e salsinha", "Arroz e batata cozida em cubos para servir"],
    steps: ["Refogue a cebola no fio de azeite e doure o frango temperado com sal e cúrcuma.",
      "Abaixe o fogo, junte 1/2 xícara de água e cozinhe 10 min.",
      "DESLIGUE o fogo e só então misture o iogurte (para não talhar).",
      "Sirva com arroz e batata cozida (a 'batata palha' aqui é assada ou cozida)."],
    tip: "Sem creme de leite, sem ketchup, sem mostarda — e a família nem nota." },

  { id: "arroz-forno", meal: "almoco", name: "Arroz de forno com frango e legumes", time: 35, portions: 4,
    tags: ["aproveitamento", "para a família"],
    ing: ["3 xícaras de arroz cozido (sobra de ontem!)", "1 xícara de frango desfiado", "1/2 abobrinha e 1/2 cenoura raladas", "2 ovos batidos", "2 col. de ricota", "Sal, orégano e salsinha"],
    steps: ["Misture tudo numa tigela grande.",
      "Transfira para um refratário untado com fio de azeite.",
      "Asse a 200 °C por 20 min, até firmar e dourar de leve."],
    tip: "O destino perfeito das sobras da semana — vira outra comida." },

  { id: "peixe-vapor", meal: "almoco", name: "Peixe no vapor com gengibre e legumes", time: 25, portions: 2,
    tags: ["leve", "moderna", "sem gordura"],
    ing: ["2 filés de peixe branco", "2 rodelas finas de gengibre", "1 cenoura e 1 abobrinha em tiras", "Sal e cebolinha", "1 fio de azeite para finalizar"],
    steps: ["Na panela com cesto de vapor (ou escorredor de metal sobre água fervente), faça uma cama de legumes.",
      "Coloque os filés por cima com o gengibre e o sal; tampe.",
      "Cozinhe no vapor 10–12 min, até o peixe ficar opaco.",
      "Finalize com cebolinha e o fio de azeite."],
    tip: "Cozinhar no vapor é o modo mais gentil que existe — nada de gordura aquecida." },

  { id: "salada-morna", meal: "almoco", name: "Salada morna de batata, vagem e ovo", time: 25, portions: 2,
    tags: ["leve", "completa", "sem carne"],
    ing: ["3 batatas em cubos", "1 xícara de vagem em pedaços", "2 ovos cozidos", "Azeite, sal, salsinha e cebolinha"],
    steps: ["Cozinhe as batatas e a vagem até ficarem macias (± 12 min).",
      "Escorra e tempere ainda mornas com azeite, sal e as ervas.",
      "Junte os ovos cozidos em quartos por cima."],
    tip: "Salada de verdade que sustenta — e morna, do jeito que o estômago gosta." },

  { id: "quibe-abobora", meal: "almoco", name: "Quibe de forno com abóbora", time: 50, portions: 4,
    tags: ["forno", "árabe adaptada"],
    ing: ["1 xícara de trigo para quibe", "300 g de patinho moído", "1 xícara de abóbora cozida amassada", "1/2 cebola picada", "Hortelã NÃO — use salsinha!", "Sal e cominho suave"],
    steps: ["Hidrate o trigo em água morna por 30 min e esprema bem.",
      "Misture com a carne, a abóbora, a cebola, a salsinha, o sal e o cominho.",
      "Espalhe em assadeira untada, marque em losangos e regue com fio de azeite.",
      "Asse a 200 °C por 30 min."],
    tip: "A abóbora deixa úmido sem precisar de gordura. E sim: trocamos a hortelã de propósito." },

  { id: "panqueca-frango", meal: "almoco", name: "Panqueca de aveia com frango", time: 40, portions: 3,
    tags: ["sem farinha branca", "para a família"],
    ing: ["Massa: 1 xícara de aveia em flocos finos, 1 ovo, 1 xícara de leite desnatado, sal", "Recheio: 2 xícaras de frango desfiado refogado com cenoura ralada", "Cobertura: molho de abóbora (da receita do macarrão)"],
    steps: ["Bata os ingredientes da massa no liquidificador; descanse 5 min.",
      "Faça discos finos na antiaderente, 1–2 min por lado.",
      "Recheie com o frango, enrole e cubra com o molho de abóbora.",
      "Forno a 180 °C por 10 min para aquecer tudo junto."],
    tip: "Panqueca sem fritura e sem molho ácido — domingo em paz." },

  { id: "lombo-batatadoce", meal: "almoco", name: "Lombo magro assado com batata-doce", time: 60, portions: 4,
    tags: ["forno", "almoço de domingo"],
    ing: ["500 g de lombo suíno limpo (sem capa de gordura)", "2 batatas-doces em rodelas grossas", "Sal, alecrim, tomilho e 1 fio de azeite", "1/2 xícara de água"],
    steps: ["Tempere o lombo com sal e as ervas (se puder, na véspera).",
      "Numa assadeira, acomode o lombo, as batatas ao redor, o fio de azeite e a água no fundo.",
      "Cubra com papel-alumínio e asse a 200 °C por 30 min; destampe e asse mais 20 para dourar.",
      "Fatie fino para servir."],
    tip: "Lombo é o corte magro do porco — assado coberto, fica macio sem fritar nada." },

  { id: "tilapia-crosta", meal: "almoco", name: "Tilápia em crosta de aveia e ervas", time: 30, portions: 2,
    tags: ["forno", "crocante sem fritura"],
    ing: ["2 filés de tilápia", "4 col. (sopa) de aveia em flocos finos", "Salsinha e cebolinha picadas", "Sal e 1 fio de azeite"],
    steps: ["Tempere os filés com sal.",
      "Misture a aveia com as ervas e um fio de azeite até virar uma farofinha úmida.",
      "Cubra os filés com a mistura, pressionando de leve.",
      "Asse a 200 °C por 15–18 min, até a crosta dourar."],
    tip: "A crocância do empanado, sem fritura e sem farinha de rosca." },

  /* ---------- AMPLIAÇÃO: JANTAR ---------- */
  { id: "creme-inhame", meal: "janta", name: "Creme de inhame com frango desfiado", time: 35, portions: 3,
    tags: ["para crises", "conforto"],
    ing: ["4 inhames descascados", "1 xícara de frango desfiado", "700 ml de água ou caldo caseiro", "1/2 cebola, sal e cebolinha"],
    steps: ["Cozinhe o inhame com a cebola no caldo até desmanchar (± 20 min).",
      "Bata no liquidificador até virar um creme aveludado.",
      "Volte à panela, junte o frango, acerte o sal e aqueça.",
      "Finalize com cebolinha."],
    tip: "O inhame tem uma cremosidade natural que abraça o estômago — clássico de recuperação." },

  { id: "caldo-verde-leve", meal: "janta", name: "Caldo verde leve (sem linguiça)", time: 40, portions: 4,
    tags: ["clássica adaptada", "conforto"],
    ing: ["4 batatas", "2 folhas de couve em tirinhas bem finas", "1 xícara de frango desfiado", "1/2 cebola, sal e 1 fio de azeite", "1 litro de água"],
    steps: ["Cozinhe as batatas com a cebola na água até amolecer; bata no liquidificador.",
      "Volte à panela, junte o frango e a couve e cozinhe 5 min.",
      "Acerte o sal e sirva com o fio de azeite."],
    tip: "A linguiça saiu, o frango dourado entrou — o aconchego ficou." },

  { id: "canjiquinha", meal: "janta", name: "Canjiquinha cremosa com frango", time: 40, portions: 4,
    tags: ["mineira", "conforto", "barata"],
    ing: ["1 xícara de canjiquinha (quirera)", "300 g de sobrecoxa sem pele ou peito", "1/2 cebola, sal, louro e cúrcuma", "Salsinha e cebolinha"],
    steps: ["Lave a canjiquinha e deixe de molho 30 min (opcional, acelera).",
      "Doure o frango temperado na panela com fio de azeite; junte a cebola.",
      "Adicione a canjiquinha, o louro e 4 xícaras de água; cozinhe em fogo baixo 25–30 min, mexendo, até cremoso.",
      "Desfie o frango dentro da panela, acerte o sal e finalize com o cheiro-verde."],
    tip: "Comida mineira de alma lavada — e a canjiquinha é milho: leve e sem glúten." },

  { id: "creme-mandioquinha", meal: "janta", name: "Creme de mandioquinha com cebolinha", time: 30, portions: 3,
    tags: ["para crises", "levíssima"],
    ing: ["4 mandioquinhas", "600 ml de água ou caldo caseiro", "1/2 cebola e sal", "Cebolinha e 1 fio de azeite"],
    steps: ["Cozinhe a mandioquinha com a cebola até desmanchar.",
      "Bata, volte à panela e acerte o sal e a textura.",
      "Sirva com cebolinha e o fio de azeite."],
    tip: "Nos dias difíceis, esta é a sopa mais suave do repertório — quase um colo." },

  { id: "crepioca-frango", meal: "janta", name: "Crepioca recheada de frango com ricota", time: 15, portions: 1,
    tags: ["rápida", "jantar leve", "proteica"],
    ing: ["1 ovo", "2 col. (sopa) de goma de tapioca", "1/2 xícara de frango desfiado", "1 col. de ricota", "Cebolinha e sal"],
    steps: ["Misture o frango com a ricota e a cebolinha.",
      "Faça a crepioca (ovo + goma + sal) na antiaderente em fogo baixo.",
      "Recheie, dobre e aqueça 1 min de cada lado."],
    tip: "Jantar em 15 minutos que não pesa para dormir." },

  { id: "ensopadinho-peixe", meal: "janta", name: "Ensopadinho de peixe (moqueca adaptada)", time: 35, portions: 3,
    tags: ["adaptada", "sem dendê"],
    ing: ["400 g de peixe branco em postas", "1 batata e 1 cenoura em rodelas", "1/2 cebola", "100 ml de leite de coco LIGHT", "Coentro (ou salsinha), sal e cúrcuma"],
    steps: ["Refogue a cebola no fio de azeite; junte a batata, a cenoura e 1 xícara de água. Cozinhe 10 min.",
      "Acomode o peixe temperado com sal e cúrcuma; cozinhe mais 8 min sem mexer.",
      "Junte o leite de coco light, aqueça 2 min e desligue.",
      "Finalize com o coentro."],
    tip: "Sem dendê, sem pimentão e com leite de coco light em pouca quantidade: o espírito da moqueca, sem o incêndio." },

  { id: "risotinho-cenoura", meal: "janta", name: "'Risotinho' de panela: arroz, cenoura e frango", time: 25, portions: 2,
    tags: ["uma panela só", "rápida"],
    ing: ["1 xícara de arroz", "1 cenoura ralada", "1 xícara de frango desfiado", "1/2 cebola picada", "3 xícaras de água quente", "Sal, cúrcuma e salsinha", "1 col. de ricota (opcional)"],
    steps: ["Refogue a cebola, junte o arroz, a cenoura e a cúrcuma.",
      "Adicione a água quente e o sal; cozinhe em fogo baixo até o arroz ficar cremoso (± 18 min), mexendo no final.",
      "Misture o frango e a ricota, finalize com salsinha."],
    tip: "Uma panela, 25 minutos, zero louça extra — o jantar de dia de semana ideal." },

  /* ---------- AMPLIAÇÃO: LANCHES & CEIA ---------- */
  { id: "pate-frango", meal: "lanche", name: "Patê de frango com iogurte", time: 10, portions: 4,
    tags: ["para o pão", "proteico", "geladeira"],
    ing: ["1 xícara de frango cozido desfiado", "3 col. (sopa) de iogurte natural desnatado", "1 col. de ricota", "Salsinha, cebolinha e sal"],
    steps: ["Bata tudo no processador (ou pique bem fino e misture).",
      "Acerte o sal e leve à geladeira por 30 min.",
      "Sirva com torradas ou pão de forma."],
    tip: "Substitui maionese e requeijão no lanche — e dura 3 dias na geladeira." },

  { id: "pasta-ricota", meal: "lanche", name: "Pasta de ricota com ervas", time: 5, portions: 4,
    tags: ["rápida", "para o pão"],
    ing: ["1 xícara de ricota fresca", "2 col. (sopa) de iogurte natural", "Salsinha, cebolinha, orégano e sal", "1 fio de azeite"],
    steps: ["Amasse a ricota com o garfo, misture o iogurte até cremoso.",
      "Tempere com as ervas, o sal e o azeite."],
    tip: "O 'requeijão' oficial da recuperação: cremoso, leve e sem gordura pesada." },

  { id: "biscoito-banana", meal: "lanche", name: "Biscoitinhos de banana e aveia (3 ingredientes)", time: 25, portions: 12,
    tags: ["forno", "sem açúcar", "para a semana"],
    ing: ["2 bananas maduras", "1 xícara de aveia em flocos", "Canela suave (o 3º ingrediente é opcional: uva-passa)"],
    steps: ["Amasse as bananas e misture com a aveia (e as passas, se quiser).",
      "Faça montinhos numa assadeira com papel-manteiga e achate de leve.",
      "Asse a 180 °C por 15–18 min."],
    tip: "O biscoito que pode: doce da fruta, fibra da aveia, zero fritura." },

  { id: "pera-cozida", meal: "lanche", name: "Pera cozida com canela suave", time: 20, portions: 2,
    tags: ["sobremesa", "para crises"],
    ing: ["2 peras descascadas e cortadas ao meio", "1 xícara de água", "1 col. (chá) de mel", "1 pauzinho pequeno de canela"],
    steps: ["Leve tudo ao fogo baixo, tampado, por 12–15 min, até a pera ficar macia.",
      "Sirva morna com um pouco da calda do cozimento."],
    tip: "Elegante o bastante para visita, suave o bastante para crise." },

  { id: "chips-batatadoce", meal: "lanche", name: "Chips de batata-doce na airfryer", time: 20, portions: 2,
    tags: ["airfryer", "crocante", "sem fritura"],
    ing: ["1 batata-doce em fatias BEM finas (use mandolina ou faca afiada)", "1 fio de azeite", "Sal e alecrim"],
    steps: ["Misture as fatias com o fio de azeite, o sal e o alecrim.",
      "Airfryer a 160 °C por 12–15 min, chacoalhando a cada 5, até crocantes.",
      "Deixe esfriar 2 min — é quando terminam de endurecer."],
    tip: "Mata a vontade de salgadinho. Coma uma porção pequena e guarde o resto em pote fechado." },

  { id: "homus-suave", meal: "lanche", name: "Homus suave com palitos de legumes", time: 15, portions: 4,
    tags: ["moderna", "proteína vegetal"],
    ing: ["1 xícara de grão-de-bico bem cozido (sem a pele, se tiver paciência)", "1 col. (sopa) de tahine", "2 col. de água do cozimento", "1 fio de azeite, sal e cominho suave (SEM limão e SEM alho cru)", "Palitos de cenoura e pepino"],
    steps: ["Bata o grão-de-bico com o tahine, a água, o sal e o cominho até bem cremoso.",
      "Regue com o fio de azeite.",
      "Sirva com os palitos de legumes."],
    tip: "Versão sem limão e sem alho cru: a cremosidade fica, a agressão sai. Porção pequena se você sente gases." },

  { id: "picole-frutas", meal: "lanche", name: "Picolé caseiro de melão ou mamão", time: 10, portions: 6,
    tags: ["gelado", "sem açúcar", "verão"],
    ing: ["2 xícaras de melão (ou mamão) picado", "1/2 banana (para dar liga)", "1 col. (chá) de mel (opcional)"],
    steps: ["Bata as frutas até virar um creme.",
      "Distribua em forminhas de picolé (ou copinhos com palito).",
      "Congele por 4 horas."],
    tip: "No calor, troca o sorvete cremoso (gatilho) por gelado de fruta que refresca sem queimar depois." },

  { id: "cha-noite", meal: "lanche", name: "Chá calmante da noite (camomila + erva-doce)", time: 10, portions: 1,
    tags: ["chá terapêutico", "para dormir"],
    ing: ["1 col. (chá) de flores de camomila", "1 col. (chá) de sementes de erva-doce", "1 xícara (200 ml) de água quente"],
    steps: ["Ferva a água e desligue.",
      "Junte a camomila e a erva-doce, tampe e abafe 8–10 min.",
      "Coe e tome morno, 1h antes de deitar."],
    tip: "Ritual da ceia: acalma o estômago E a cabeça — os dois culpados do refluxo noturno." },
];

/* =========================================================
   SAFRA — produtos da estação por mês (calendário aproximado,
   base CEAGESP/Sudeste; varia conforme a região)
   ========================================================= */
const SEASONAL = [
  { frutas: ["Banana-prata", "Mamão", "Melão", "Uva niágara doce", "Figo", "Pera-d'água"],
    legumes: ["Abobrinha", "Pepino", "Beterraba", "Milho-verde", "Vagem", "Alface"] },
  { frutas: ["Banana-nanica", "Mamão-formosa", "Goiaba", "Uva itália", "Pera", "Maçã-gala"],
    legumes: ["Abóbora-menina", "Abobrinha", "Berinjela", "Chuchu", "Quiabo", "Alface"] },
  { frutas: ["Banana-maçã", "Goiaba", "Mamão", "Maçã-fuji", "Caqui doce", "Coco-verde"],
    legumes: ["Abóbora-japonesa", "Berinjela", "Beterraba", "Chuchu", "Couve", "Milho-verde"] },
  { frutas: ["Caqui doce", "Banana", "Goiaba", "Maçã", "Pera-portuguesa", "Mamão"],
    legumes: ["Abóbora", "Batata-doce", "Berinjela", "Brócolis", "Chuchu", "Mandioquinha"] },
  { frutas: ["Banana", "Caqui", "Maçã", "Mamão", "Melão", "Abacate"],
    legumes: ["Abóbora", "Batata-doce", "Brócolis", "Cará", "Inhame", "Mandioquinha"] },
  { frutas: ["Banana", "Maçã", "Mamão", "Melão", "Pera", "Abacate"],
    legumes: ["Abóbora", "Batata-doce", "Brócolis", "Cará", "Cenoura", "Inhame"] },
  { frutas: ["Banana", "Maçã", "Mamão-formosa", "Melão-amarelo", "Pera"],
    legumes: ["Abóbora-cabotiá", "Batata-doce", "Cará", "Cenoura", "Couve-flor", "Inhame", "Mandioquinha"] },
  { frutas: ["Banana", "Mamão", "Melão", "Maçã", "Pera"],
    legumes: ["Abobrinha", "Batata-doce", "Beterraba", "Cenoura", "Chuchu", "Couve", "Inhame"] },
  { frutas: ["Banana", "Mamão", "Melão", "Melancia", "Pera"],
    legumes: ["Abobrinha", "Beterraba", "Cenoura", "Chuchu", "Couve", "Vagem"] },
  { frutas: ["Banana", "Mamão", "Melão", "Melancia", "Manga madura"],
    legumes: ["Abobrinha", "Beterraba", "Cenoura", "Pepino", "Vagem", "Alface"] },
  { frutas: ["Banana", "Mamão", "Melancia", "Melão", "Manga", "Figo"],
    legumes: ["Abobrinha", "Beterraba", "Milho-verde", "Pepino", "Vagem", "Alface"] },
  { frutas: ["Banana", "Mamão", "Melancia", "Manga", "Figo", "Uva doce"],
    legumes: ["Abobrinha", "Beterraba", "Milho-verde", "Pepino", "Vagem", "Alface"] },
];

/* =========================================================
   DICAS — educação em pequenas doses
   ========================================================= */
const TIPS = [
  { cat: "Alimentação", icon: "🍽️", title: "Coma a cada 3 horas",
    text: "Porções pequenas e frequentes evitam tanto o estômago vazio (que dói) quanto o muito cheio (que reflui). Use os alarmes do app para criar o hábito." },
  { cat: "Alimentação", icon: "🐢", title: "Mastigue devagar — de verdade",
    text: "Mastigue cada garfada 20–30 vezes e apoie os talheres entre uma e outra. A digestão começa na boca, e comer rápido engole ar e sobrecarrega o estômago." },
  { cat: "Alimentação", icon: "💧", title: "Água entre as refeições, não durante",
    text: "Grandes volumes de líquido junto com a comida distendem o estômago. Beba pequenos goles ao longo do dia e evite copos cheios durante as refeições." },
  { cat: "Alimentação", icon: "🌡️", title: "Prefira comida morna",
    text: "Alimentos muito quentes ou muito gelados irritam a mucosa inflamada. Morno é a temperatura da recuperação." },
  { cat: "Refluxo noturno", icon: "🛏️", title: "Última refeição 3 horas antes de deitar",
    text: "Deitar com o estômago cheio é receita de refluxo noturno. Jante cedo e leve — o app avisa se seu jantar está muito perto do horário de dormir." },
  { cat: "Refluxo noturno", icon: "📐", title: "Eleve a cabeceira da cama (10–15 cm)",
    text: "Calços sob os pés da cabeceira ou travesseiro anti-refluxo (em cunha) usam a gravidade a seu favor. Empilhar travesseiros comuns não funciona — dobra o abdômen e piora." },
  { cat: "Refluxo noturno", icon: "🧭", title: "Durma do lado esquerdo",
    text: "Nessa posição, a entrada do estômago fica acima do nível do ácido, dificultando o refluxo. Pequeno truque, grande diferença." },
  { cat: "Estilo de vida", icon: "👖", title: "Evite roupas apertadas na cintura",
    text: "Cintos e calças justas pressionam o abdômen e empurram o ácido para cima, principalmente depois de comer." },
  { cat: "Estilo de vida", icon: "⚖️", title: "Perder peso reduz o refluxo",
    text: "Se há sobrepeso, cada quilo a menos diminui a pressão sobre o estômago. Acompanhe sua evolução na aba Peso & Metas." },
  { cat: "Estilo de vida", icon: "🚭", title: "Cigarro é inimigo direto",
    text: "A nicotina relaxa a válvula do esôfago e reduz a saliva que protege a mucosa. Parar de fumar melhora a gastrite e o refluxo." },
  { cat: "Estilo de vida", icon: "🧘", title: "Cuide da 'gastrite nervosa'",
    text: "Estresse e ansiedade aumentam a acidez. Caminhada leve, respiração profunda (4 s inspira, 6 s solta) e o chá de camomila da noite são tratamento também." },
  { cat: "Estilo de vida", icon: "🚶", title: "Caminhe após as refeições — não deite",
    text: "Uma caminhada leve de 10 minutos ajuda o esvaziamento do estômago. Deitar no sofá logo após comer tem o efeito oposto." },
  { cat: "Tratamento", icon: "💊", title: "Remédio na hora certa funciona melhor",
    text: "Omeprazol e similares (IBPs) agem melhor em jejum, 30–60 min antes do café da manhã. Configure o lembrete no app e siga SEMPRE a orientação do seu médico." },
  { cat: "Tratamento", icon: "📔", title: "Registre para descobrir seus gatilhos",
    text: "Cada pessoa reage diferente. Use o Diário: anote o que comeu e os sintomas — em 2 semanas os padrões aparecem e você descobre os SEUS gatilhos." },
  { cat: "Tratamento", icon: "🩺", title: "Sinais de alerta — procure o médico",
    text: "Dor intensa, vômitos persistentes, dificuldade para engolir, emagrecimento sem explicação, fezes escuras ou sangue: não espere, procure atendimento." },
];

const DEFAULT_MEALS = [
  { id: "m-cafe",    name: "Café da manhã", time: "07:00", alarm: true, icon: "🌅" },
  { id: "m-lanche1", name: "Lanche da manhã", time: "10:00", alarm: true, icon: "🍎" },
  { id: "m-almoco",  name: "Almoço", time: "12:30", alarm: true, icon: "🍽️" },
  { id: "m-lanche2", name: "Lanche da tarde", time: "15:30", alarm: true, icon: "🥪" },
  { id: "m-janta",   name: "Jantar", time: "18:30", alarm: true, icon: "🌙" },
  { id: "m-ceia",    name: "Ceia leve", time: "20:30", alarm: false, icon: "🍵" },
];

const SYMPTOMS = [
  { id: "azia",     name: "Azia / queimação", icon: "🔥" },
  { id: "refluxo",  name: "Refluxo / regurgitação", icon: "🌊" },
  { id: "dor",      name: "Dor no estômago", icon: "😖" },
  { id: "nausea",   name: "Náusea / enjoo", icon: "🤢" },
  { id: "estufado", name: "Estufamento / gases", icon: "🎈" },
  { id: "garganta", name: "Garganta irritada / tosse", icon: "😮‍💨" },
];

const GOAL_SUGGESTIONS = [
  "30 dias sem café",
  "Jantar 3h antes de dormir",
  "Zero fritura esta semana",
  "Chá calmante toda noite",
  "Mastigar devagar em todas as refeições",
  "Caminhar 10 min após o almoço",
  "Sem chocolate por 21 dias",
  "Sem refrigerante por 30 dias",
];

const MONTH_NAMES = ["Janeiro","Fevereiro","Março","Abril","Maio","Junho",
  "Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"];
