/* =========================================================
   GastroCuida — Base de conteúdo
   Guia alimentar, chás, receitas, safra e dicas para quem
   convive com gastrite e refluxo (DRGE).
   Conteúdo educativo — não substitui orientação médica.
   ========================================================= */

// Status possíveis: "ok" (pode), "mod" (com moderação), "no" (evitar), "care" (cautela/orientação médica)
const STATUS = {
  ok:   { label: "Pode",       icon: "✅" },
  mod:  { label: "Moderação",  icon: "⚠️" },
  no:   { label: "Evitar",     icon: "🚫" },
  care: { label: "Cautela",    icon: "❗" },
};

const FOOD_CATEGORIES = [
  { id: "carnes",   name: "Carnes & Peixes",      icon: "🍗" },
  { id: "ovos",     name: "Ovos",                 icon: "🥚" },
  { id: "frutas",   name: "Frutas",               icon: "🍌" },
  { id: "legumes",  name: "Verduras & Legumes",   icon: "🥕" },
  { id: "raizes",   name: "Raízes & Tubérculos",  icon: "🍠" },
  { id: "graos",    name: "Grãos, Pães & Cereais",icon: "🌾" },
  { id: "laticinios", name: "Laticínios",         icon: "🥛" },
  { id: "chas",     name: "Chás & Ervas",         icon: "🍵" },
  { id: "bebidas",  name: "Bebidas",              icon: "🥤" },
  { id: "temperos", name: "Temperos",             icon: "🧂" },
  { id: "doces",    name: "Doces & Sobremesas",   icon: "🍮" },
];

const FOODS = [
  // ---------------- CARNES & PEIXES ----------------
  { cat: "carnes", name: "Frango sem pele", status: "ok",
    note: "Grelhado, cozido, desfiado ou na airfryer. A proteína mais amiga do estômago — sempre sem a pele e sem fritar." },
  { cat: "carnes", name: "Tilápia, merluza, pescada (peixes brancos)", status: "ok",
    note: "Assados, cozidos ou em papelote. Digestão leve e rápida — ótimos para o jantar." },
  { cat: "carnes", name: "Carne bovina magra (patinho, músculo, lagarto)", status: "ok",
    note: "Cozida, assada ou moída refogada com pouco óleo. Retire toda a gordura aparente." },
  { cat: "carnes", name: "Salmão", status: "mod",
    note: "Rico em ômega-3, mas mais gorduroso. Grelhado, em porções pequenas, e observe como você reage." },
  { cat: "carnes", name: "Sardinha fresca assada", status: "mod",
    note: "Boa fonte de ômega-3. Prefira fresca e assada; evite a enlatada em óleo." },
  { cat: "carnes", name: "Lombo suíno magro", status: "mod",
    note: "É o corte magro do porco. Assado e em pouca quantidade. Evite os cortes gordos." },
  { cat: "carnes", name: "Carnes gordas (picanha, cupim, costela)", status: "no",
    note: "Gordura retarda o esvaziamento do estômago e relaxa a válvula que segura o refluxo." },
  { cat: "carnes", name: "Frituras e milanesas", status: "no",
    note: "Fritura é um dos maiores gatilhos de azia. Troque pela airfryer ou forno." },
  { cat: "carnes", name: "Embutidos (linguiça, salsicha, bacon, presunto, salame, mortadela)", status: "no",
    note: "Gordura + sal + conservantes irritam a mucosa. Inclui peito de peru de pacote." },
  { cat: "carnes", name: "Carnes defumadas e churrasco com muita gordura", status: "no",
    note: "Defumação e gordura queimada agridem o estômago inflamado." },

  // ---------------- OVOS ----------------
  { cat: "ovos", name: "Ovo cozido", status: "ok",
    note: "A forma mais leve. Cozinhe 8–10 min. Vai bem no lanche, na salada e no prato principal." },
  { cat: "ovos", name: "Ovo pochê", status: "ok",
    note: "Cozido na água sem nenhuma gordura. Fica cremoso e é super digesto." },
  { cat: "ovos", name: "Ovo mexido cremoso (sem gordura)", status: "ok",
    note: "Na frigideira antiaderente, fogo baixo, mexendo sempre. Sem manteiga ou com 1 fio de azeite." },
  { cat: "ovos", name: "Omelete de forno ou frigideira antiaderente", status: "ok",
    note: "Com legumes permitidos (abobrinha, cenoura, espinafre). Asse ou use pouquíssimo azeite." },
  { cat: "ovos", name: "Crepioca (ovo + tapioca)", status: "ok",
    note: "Mistura moderna e prática: 1 ovo + 2 col. de goma de tapioca. Recheie com queijo branco." },
  { cat: "ovos", name: "Ovo frito em óleo ou manteiga", status: "no",
    note: "A gordura da fritura é o problema, não o ovo. Prefira as versões acima." },

  // ---------------- FRUTAS ----------------
  { cat: "frutas", name: "Banana (prata, nanica) madura", status: "ok",
    note: "Suave e levemente alcalina, protege a mucosa. Ótima para lanches e receitas." },
  { cat: "frutas", name: "Mamão", status: "ok",
    note: "Tem papaína, enzima que ajuda a digestão. Excelente no café da manhã." },
  { cat: "frutas", name: "Melão", status: "ok",
    note: "Pouco ácido e hidratante. Vai bem em qualquer hora do dia." },
  { cat: "frutas", name: "Pera", status: "ok",
    note: "Leve e rica em fibras suaves. Pode assar com canela para a sobremesa." },
  { cat: "frutas", name: "Maçã", status: "ok",
    note: "Prefira madura; em crise, sem casca ou cozida/assada fica ainda mais suave." },
  { cat: "frutas", name: "Goiaba madura", status: "ok",
    note: "Bem tolerada quando madura. Evite verde (adstringente)." },
  { cat: "frutas", name: "Melancia", status: "mod",
    note: "Costuma ser tolerada, mas o volume de líquido incomoda algumas pessoas. Teste porções pequenas." },
  { cat: "frutas", name: "Manga madura", status: "mod",
    note: "Doce e suave quando bem madura. Verde é ácida — evite." },
  { cat: "frutas", name: "Abacate", status: "mod",
    note: "Gordura boa, mas gordura ainda assim. Porções pequenas (2 colheres)." },
  { cat: "frutas", name: "Uva doce (niágara, itália)", status: "mod",
    note: "Bem madura e doce costuma ser tolerada. Evite as mais azedinhas." },
  { cat: "frutas", name: "Caqui, figo, ameixa doce", status: "mod",
    note: "Frutas doces geralmente bem toleradas fora das crises." },
  { cat: "frutas", name: "Laranja, limão, tangerina, acerola", status: "no",
    note: "Cítricas: aumentam a acidez e pioram azia — principalmente em jejum e nas crises." },
  { cat: "frutas", name: "Abacaxi, maracujá, kiwi, morango", status: "no",
    note: "Ácidas para o estômago inflamado. Reintroduza só depois, com orientação." },
  { cat: "frutas", name: "Tomate (e molho de tomate)", status: "no",
    note: "É uma fruta ácida! Molhos concentrados são gatilho clássico de refluxo." },

  // ---------------- VERDURAS & LEGUMES ----------------
  { cat: "legumes", name: "Abobrinha", status: "ok",
    note: "Curinga da dieta: refogada, assada, em sopas e omeletes. Digestão facílima." },
  { cat: "legumes", name: "Chuchu", status: "ok",
    note: "Neutro e suave — perfeito para o estômago sensível." },
  { cat: "legumes", name: "Cenoura", status: "ok",
    note: "Cozida, crua ralada (fora de crise), em purês e sopas." },
  { cat: "legumes", name: "Abóbora / moranga / cabotiá", status: "ok",
    note: "Doce natural, cremosa em purês e sopas. Rica em betacaroteno, que ajuda na cicatrização." },
  { cat: "legumes", name: "Vagem", status: "ok",
    note: "Cozida no vapor fica leve e mantém os nutrientes." },
  { cat: "legumes", name: "Beterraba cozida", status: "ok",
    note: "Suave e nutritiva. Cozida ou assada." },
  { cat: "legumes", name: "Espinafre e couve refogados", status: "ok",
    note: "Refogue rapidamente com um fio de azeite. Fontes de ferro e folato." },
  { cat: "legumes", name: "Alface", status: "ok",
    note: "Folha mais leve para saladas. Higienize bem." },
  { cat: "legumes", name: "Berinjela e quiabo cozidos", status: "ok",
    note: "Bem cozidos são suaves. Evite berinjela frita ou empanada." },
  { cat: "legumes", name: "Brócolis e couve-flor cozidos", status: "mod",
    note: "Saudáveis, mas podem dar gases e estufamento. Cozinhe bem e teste porções pequenas." },
  { cat: "legumes", name: "Repolho cozido", status: "mod",
    note: "Mesmo caso: bem cozido e em pouca quantidade para não fermentar." },
  { cat: "legumes", name: "Pepino sem casca", status: "mod",
    note: "Algumas pessoas digerem mal. Sem casca e sem sementes é mais leve." },
  { cat: "legumes", name: "Cebola e alho cozidos/refogados", status: "mod",
    note: "Refogados e em pequena quantidade costumam ser tolerados." },
  { cat: "legumes", name: "Cebola e alho crus", status: "no",
    note: "Crus são irritantes e gatilho comum de azia." },
  { cat: "legumes", name: "Pimentão", status: "no",
    note: "Digestão difícil e queixa clássica de quem tem gastrite." },

  // ---------------- RAÍZES & TUBÉRCULOS ----------------
  { cat: "raizes", name: "Aipim / mandioca / macaxeira", status: "ok",
    note: "Cozida é energia leve e sem glúten. Rende purê, escondidinho e até 'cuscuz' de raiz." },
  { cat: "raizes", name: "Inhame", status: "ok",
    note: "Cremoso e suave, protege a mucosa. Cozido, em purê ou engrossando sopas." },
  { cat: "raizes", name: "Cará", status: "ok",
    note: "Primo do inhame, mesmo uso: purês, sopas e cozidos. Muito bem tolerado." },
  { cat: "raizes", name: "Batata-doce", status: "ok",
    note: "Assada ou cozida. Energia de digestão tranquila — ótima no pós-treino também." },
  { cat: "raizes", name: "Batata inglesa", status: "ok",
    note: "Cozida, assada ou em purê (com leite desnatado). Nunca frita." },
  { cat: "raizes", name: "Mandioquinha (batata-baroa)", status: "ok",
    note: "A rainha dos purês e sopas cremosas. Suave e nutritiva." },

  // ---------------- GRÃOS, PÃES & CEREAIS ----------------
  { cat: "graos", name: "Arroz branco", status: "ok",
    note: "Base segura de qualquer refeição. Bem cozido e soltinho." },
  { cat: "graos", name: "Aveia", status: "ok",
    note: "Mingau, overnight oats, panquecas. As fibras solúveis acalmam o estômago." },
  { cat: "graos", name: "Cuscuz de milho (nordestino)", status: "ok",
    note: "Leve, sem glúten e versátil: com ovo mexido, queijo branco ou frango desfiado." },
  { cat: "graos", name: "Tapioca", status: "ok",
    note: "Recheios leves: queijo minas, ricota, banana. Evite recheios gordurosos." },
  { cat: "graos", name: "Pão de forma simples / pão francês", status: "ok",
    note: "Tolerado pela maioria. Se sentir peso, tire o miolo ou toste levemente." },
  { cat: "graos", name: "Macarrão com molhos leves", status: "ok",
    note: "Com azeite e legumes, ou molho de abóbora/cenoura no lugar do tomate." },
  { cat: "graos", name: "Arroz integral e quinoa", status: "mod",
    note: "Ótimos fora das crises. Em crise, o excesso de fibra pode incomodar — volte ao branco." },
  { cat: "graos", name: "Feijão, lentilha, grão-de-bico", status: "mod",
    note: "Comece pelo caldo e porções pequenas. Deixe de molho antes de cozinhar para reduzir gases." },
  { cat: "graos", name: "Granolas açucaradas e biscoitos recheados", status: "no",
    note: "Açúcar + gordura escondida. Prefira aveia com fruta." },

  // ---------------- LATICÍNIOS ----------------
  { cat: "laticinios", name: "Iogurte natural desnatado", status: "ok",
    note: "Probióticos ajudam a flora e a digestão. Sem açúcar; adoce com fruta." },
  { cat: "laticinios", name: "Queijo minas frescal, ricota, cottage", status: "ok",
    note: "Queijos brancos e magros — os únicos liberados de verdade." },
  { cat: "laticinios", name: "Leite desnatado", status: "mod",
    note: "Alivia na hora, mas pode causar 'efeito rebote' de acidez. Pequenas quantidades." },
  { cat: "laticinios", name: "Queijos amarelos (mussarela, prato, parmesão)", status: "mod",
    note: "Gordurosos. Uma fatia fina esporádica, fora das crises." },
  { cat: "laticinios", name: "Leite integral, creme de leite, requeijão", status: "no",
    note: "Gordura láctea piora refluxo e retarda a digestão." },

  // ---------------- CHÁS & ERVAS ----------------
  { cat: "chas", name: "Espinheira-santa", status: "ok",
    note: "A erva clássica para gastrite e azia, reconhecida como fitoterápico no Brasil. Preparo: 1 col. (sopa) de folhas para 1 xícara de água quente, abafe 10 min. Tome 2–3x ao dia, de preferência 30 min antes das refeições. ⚠️ Contraindicada para gestantes e lactantes.", featured: true },
  { cat: "chas", name: "Camomila", status: "ok",
    note: "Calmante e anti-inflamatória suave — ótima à noite e nos dias de 'gastrite nervosa'." },
  { cat: "chas", name: "Erva-doce (funcho)", status: "ok",
    note: "Digestiva e boa contra gases e estufamento. Pode misturar com camomila." },
  { cat: "chas", name: "Melissa (erva-cidreira)", status: "ok",
    note: "Acalma o estômago e a ansiedade. Boa para a ceia, 1h antes de dormir." },
  { cat: "chas", name: "Gengibre", status: "mod",
    note: "Excelente contra náusea, mas em excesso pode arder. Faça chá fraco (2–3 rodelas finas) e observe." },
  { cat: "chas", name: "Boldo", status: "mod",
    note: "Digestivo amargo tradicional. Uso pontual após refeições pesadas; evite na gestação." },
  { cat: "chas", name: "Alcaçuz", status: "mod",
    note: "Usado para proteger a mucosa. Cuidado se você tem pressão alta — converse com o médico." },
  { cat: "chas", name: "Babosa (aloe vera)", status: "care",
    note: "Usada popularmente para gastrite, MAS o preparo caseiro é arriscado: a casca e o látex amarelo são tóxicos e laxativos. A Anvisa não recomenda ingerir babosa preparada em casa. Se quiser usar, escolha somente produtos de gel de aloe próprios para consumo oral, com registro, e SEMPRE com aval do seu médico.", featured: true },
  { cat: "chas", name: "Hortelã-pimenta", status: "no",
    note: "Surpresa: hortelã relaxa a válvula do esôfago e PIORA o refluxo. Evite chá e balas de menta." },
  { cat: "chas", name: "Chá preto, verde, branco e mate", status: "no",
    note: "Todos têm cafeína, que estimula a acidez. Troque pelos chás calmantes acima." },

  // ---------------- BEBIDAS ----------------
  { cat: "bebidas", name: "Água", status: "ok",
    note: "Em pequenos goles ao longo do dia. Evite volumes grandes junto com as refeições." },
  { cat: "bebidas", name: "Água de coco", status: "ok",
    note: "Hidratante e suave. Boa opção entre as refeições." },
  { cat: "bebidas", name: "Suco de melão, pera ou mamão (natural)", status: "ok",
    note: "Sucos de frutas não ácidas, sem açúcar, coados se estiver em crise." },
  { cat: "bebidas", name: "Café", status: "no",
    note: "Cafeína aumenta a acidez e relaxa a válvula do esôfago. É dos gatilhos mais fortes — inclusive o descafeinado incomoda algumas pessoas." },
  { cat: "bebidas", name: "Refrigerante e água com gás", status: "no",
    note: "O gás distende o estômago e empurra o ácido para cima." },
  { cat: "bebidas", name: "Álcool (cerveja, vinho, destilados)", status: "no",
    note: "Irrita a mucosa diretamente e piora o refluxo. Evite durante o tratamento." },
  { cat: "bebidas", name: "Sucos cítricos e energéticos", status: "no",
    note: "Acidez + cafeína. Fuja durante a recuperação." },

  // ---------------- TEMPEROS ----------------
  { cat: "temperos", name: "Ervas frescas (salsinha, cebolinha, coentro, manjericão)", status: "ok",
    note: "Dão sabor sem agredir. Use à vontade." },
  { cat: "temperos", name: "Ervas secas (alecrim, tomilho, louro, orégano)", status: "ok",
    note: "Aromáticas e seguras em quantidades normais de tempero." },
  { cat: "temperos", name: "Cúrcuma (açafrão-da-terra)", status: "ok",
    note: "Anti-inflamatória natural. Colore e tempera arroz, frango e sopas." },
  { cat: "temperos", name: "Azeite de oliva extravirgem", status: "mod",
    note: "Gordura boa, mas gordura: use 1 fio para finalizar, não para fritar." },
  { cat: "temperos", name: "Sal", status: "mod",
    note: "Com parcimônia. Excesso de sal também agride a mucosa." },
  { cat: "temperos", name: "Pimentas (do reino, malagueta, dedo-de-moça)", status: "no",
    note: "Irritação direta na mucosa inflamada. Corte durante o tratamento." },
  { cat: "temperos", name: "Molhos prontos (ketchup, mostarda, shoyu, inglês) e caldos em cubo", status: "no",
    note: "Ácidos, salgados e cheios de aditivos. Tempere com ervas de verdade." },
  { cat: "temperos", name: "Vinagre", status: "no",
    note: "Ácido puro na salada. Troque por um fio de azeite com ervas." },

  // ---------------- DOCES ----------------
  { cat: "doces", name: "Frutas assadas (banana ou maçã com canela suave)", status: "ok",
    note: "A sobremesa oficial da recuperação: doce natural, quentinha e leve." },
  { cat: "doces", name: "Gelatina", status: "ok",
    note: "Leve e refrescante. Prefira as versões com menos corante." },
  { cat: "doces", name: "Mel", status: "mod",
    note: "1 colher de chá para adoçar chás ou iogurte. Tem ação suavizante, mas é açúcar." },
  { cat: "doces", name: "Doce caseiro de banana/mamão (pouco açúcar)", status: "mod",
    note: "Feito em casa, sem excesso de açúcar, em porção pequena." },
  { cat: "doces", name: "Chocolate", status: "no",
    note: "Cafeína + gordura + relaxa a válvula do esôfago. Um dos gatilhos mais traiçoeiros." },
  { cat: "doces", name: "Sobremesas cremosas e gordurosas (tortas, sorvetes, brigadeiro)", status: "no",
    note: "Gordura + açúcar em dose alta. Deixe para depois da recuperação, com moderação." },
];

/* =========================================================
   RECEITAS — fáceis, modernas e amigas do estômago
   ========================================================= */
const MEAL_TYPES = [
  { id: "cafe",   name: "Café da manhã", icon: "🌅" },
  { id: "almoco", name: "Almoço",        icon: "🍽️" },
  { id: "janta",  name: "Jantar",        icon: "🌙" },
  { id: "lanche", name: "Lanches & Ceia",icon: "🍎" },
];

const RECIPES = [
  // ---------- CAFÉ DA MANHÃ ----------
  { id: "crepioca", meal: "cafe", name: "Crepioca de queijo minas", time: 10, portions: 1,
    tags: ["rápida", "sem glúten", "proteica"],
    ing: ["1 ovo", "2 col. (sopa) de goma de tapioca", "1 pitada de sal", "2 fatias de queijo minas frescal", "Cebolinha picada (opcional)"],
    steps: ["Misture o ovo, a tapioca e o sal até ficar homogêneo.",
      "Despeje em frigideira antiaderente quente, em fogo baixo, sem gordura.",
      "Quando firmar as bordas (± 2 min), vire com uma espátula.",
      "Coloque o queijo, dobre ao meio e sirva com a cebolinha."],
    tip: "Versão doce: recheie com banana amassada e um toque de canela suave." },

  { id: "cuscuz-ovo", meal: "cafe", name: "Cuscuz nordestino com ovo mexido cremoso", time: 15, portions: 2,
    tags: ["sem glúten", "clássica", "barata"],
    ing: ["1 xícara de flocão de milho", "1/2 xícara de água", "Sal a gosto", "2 ovos", "1 col. (sopa) de leite desnatado", "1 fio de azeite"],
    steps: ["Hidrate o flocão com a água e o sal por 10 min.",
      "Cozinhe na cuscuzeira (ou no micro-ondas, 3 min em pote furado) até firmar.",
      "Bata os ovos com o leite. Cozinhe em fogo BAIXO na antiaderente, mexendo sempre, até ficar cremoso.",
      "Sirva o ovo sobre o cuscuz com um fio de azeite."],
    tip: "Fogo baixo é o segredo do ovo cremoso sem precisar de manteiga." },

  { id: "overnight", meal: "cafe", name: "Overnight oats de banana e mamão", time: 5, portions: 1,
    tags: ["rápida", "sem cozinhar", "moderna"],
    ing: ["4 col. (sopa) de aveia em flocos", "150 ml de leite desnatado ou bebida vegetal de arroz", "1/2 banana madura amassada", "2 col. de mamão picado", "1 col. (chá) de mel (opcional)"],
    steps: ["Num pote com tampa, misture a aveia, o leite e a banana amassada.",
      "Feche e deixe na geladeira de um dia para o outro (ou 30 min, se tiver pressa).",
      "Na hora de comer, cubra com o mamão e o mel."],
    tip: "Prepare 2–3 potes de uma vez: café da manhã pronto para os próximos dias." },

  { id: "panqueca-banana", meal: "cafe", name: "Panqueca de banana e aveia (3 ingredientes)", time: 12, portions: 1,
    tags: ["rápida", "sem açúcar", "moderna"],
    ing: ["1 banana madura", "1 ovo", "3 col. (sopa) de aveia em flocos finos", "Canela suave (opcional)"],
    steps: ["Amasse bem a banana e misture com o ovo e a aveia.",
      "Despeje pequenas porções na frigideira antiaderente, fogo baixo.",
      "Doure 2 min de cada lado, virando com cuidado.",
      "Finalize com uma pitada leve de canela."],
    tip: "Quanto mais madura a banana, mais doce a panqueca — sem precisar de açúcar." },

  { id: "mingau-maca", meal: "cafe", name: "Mingau de aveia com maçã cozida", time: 15, portions: 1,
    tags: ["conforto", "para crises"],
    ing: ["3 col. (sopa) de aveia", "200 ml de leite desnatado ou água", "1/2 maçã sem casca em cubinhos", "1 col. (chá) de mel", "Canela suave"],
    steps: ["Cozinhe a maçã com 2 col. de água até amolecer (± 5 min).",
      "Junte a aveia e o leite; mexa em fogo baixo até engrossar.",
      "Adoce com o mel e polvilhe canela de leve."],
    tip: "Receita coringa para os dias de crise: morna, macia e calmante." },

  { id: "tapioca-ricota", meal: "cafe", name: "Tapioca de ricota temperada com cenoura", time: 10, portions: 1,
    tags: ["rápida", "sem glúten"],
    ing: ["3 col. (sopa) de goma de tapioca", "3 col. (sopa) de ricota amassada", "2 col. de cenoura ralada fina", "Salsinha e sal a gosto"],
    steps: ["Misture a ricota com a cenoura, a salsinha e o sal.",
      "Espalhe a goma na frigideira quente e aguarde firmar (± 2 min).",
      "Recheie, dobre e sirva."],
    tip: "A cenoura ralada dá crocância suave sem pesar." },

  { id: "vitamina-mamao", meal: "cafe", name: "Vitamina de mamão com aveia", time: 5, portions: 1,
    tags: ["rápida", "líquida", "para crises"],
    ing: ["1 fatia grossa de mamão", "150 ml de leite desnatado ou bebida de arroz", "1 col. (sopa) de aveia", "Gelo (opcional)"],
    steps: ["Bata tudo no liquidificador até ficar cremoso.", "Sirva em seguida."],
    tip: "Nos dias em que mastigar incomoda, uma vitamina resolve o café da manhã." },

  // ---------- ALMOÇO ----------
  { id: "frango-inhame", meal: "almoco", name: "Frango grelhado com purê de inhame", time: 35, portions: 2,
    tags: ["clássica", "proteica"],
    ing: ["2 filés de frango", "Sal, cúrcuma e ervas (tomilho ou orégano)", "4 inhames médios", "1 fio de azeite", "Salsinha"],
    steps: ["Cozinhe os inhames descascados até ficarem macios (± 15 min); amasse com sal e um fio de azeite.",
      "Tempere o frango com sal, cúrcuma e as ervas.",
      "Grelhe na antiaderente em fogo médio, 4–5 min por lado, sem deixar queimar.",
      "Sirva sobre o purê com salsinha por cima."],
    tip: "O purê de inhame é cremoso naturalmente — não precisa de manteiga nem creme." },

  { id: "papelote", meal: "almoco", name: "Peixe em papelote com legumes", time: 30, portions: 2,
    tags: ["forno", "leve", "moderna"],
    ing: ["2 filés de tilápia ou merluza", "1 abobrinha em rodelas", "1 cenoura em tiras finas", "Sal, ervas finas e 1 fio de azeite", "Papel-manteiga ou alumínio"],
    steps: ["Corte 2 folhas grandes de papel. No centro de cada uma, faça uma cama de legumes.",
      "Coloque o filé por cima, tempere e regue com o azeite.",
      "Feche bem os pacotinhos e asse a 200 °C por 20 min.",
      "Abra o papelote no prato — o vapor perfumado é o show."],
    tip: "Técnica de restaurante, zero fritura e quase nenhuma louça." },

  { id: "escondidinho", meal: "almoco", name: "Escondidinho de aipim com frango", time: 45, portions: 4,
    tags: ["conforto", "para a família", "sem glúten"],
    ing: ["500 g de aipim (mandioca) cozido", "300 g de frango cozido e desfiado", "1/2 cebola picada refogada", "Cenoura ralada", "Salsinha, sal e cúrcuma", "2 col. de ricota ou queijo minas para gratinar"],
    steps: ["Amasse o aipim ainda quente com um pouco da água do cozimento até virar purê.",
      "Refogue a cebola no fio de azeite, junte o frango, a cenoura, a cúrcuma e a salsinha.",
      "Monte em um refratário: frango embaixo, purê por cima, queijo esfarelado no topo.",
      "Leve ao forno a 200 °C por 15 min para gratinar de leve."],
    tip: "Rende marmitas ótimas — congele em porções individuais." },

  { id: "airfryer-frango", meal: "almoco", name: "Frango na airfryer com batata-doce", time: 30, portions: 2,
    tags: ["airfryer", "moderna", "sem fritura"],
    ing: ["2 sobrecoxas sem pele ou filés", "1 batata-doce grande em cubos", "Sal, alecrim e cúrcuma", "1 fio de azeite"],
    steps: ["Tempere o frango e a batata-doce com sal, alecrim, cúrcuma e o fio de azeite.",
      "Airfryer a 180 °C: batata-doce por 20 min, chacoalhando na metade.",
      "Frango por 18–20 min, virando na metade, até dourar.",
      "Sirva com salada de alface e cenoura."],
    tip: "A airfryer dá a crocância da fritura sem o óleo que provoca a azia." },

  { id: "bowl-frango", meal: "almoco", name: "Bowl de arroz, frango desfiado e legumes", time: 25, portions: 2,
    tags: ["moderna", "marmita", "equilibrada"],
    ing: ["1 xícara de arroz cozido", "1 xícara de frango desfiado", "1/2 abobrinha em cubinhos refogada", "1/2 cenoura ralada", "Folhas de alface", "Azeite, sal e cebolinha"],
    steps: ["Monte o bowl em camadas: arroz na base, frango, abobrinha e cenoura em setores.",
      "Complete com as folhas, o fio de azeite e a cebolinha.",
      "Misture na hora de comer."],
    tip: "Fórmula do bowl perfeito: 1 base + 1 proteína + 2 legumes + 1 folha." },

  { id: "carne-mandioquinha", meal: "almoco", name: "Carne magra cozida com mandioquinha", time: 50, portions: 4,
    tags: ["panela de pressão", "conforto"],
    ing: ["500 g de músculo ou patinho em cubos", "3 mandioquinhas em pedaços", "1 cenoura em rodelas", "1/2 cebola, sal, louro e salsinha"],
    steps: ["Doure levemente a carne na própria panela de pressão com um fio de azeite.",
      "Junte a cebola, cubra com água, adicione o louro e cozinhe na pressão por 25 min.",
      "Abra, acrescente a mandioquinha e a cenoura e cozinhe mais 10 min sem pressão.",
      "Acerte o sal e finalize com salsinha. O caldo engrossa naturalmente."],
    tip: "Carne bem cozida e desmanchando é muito mais fácil de digerir do que grelhados malpassados." },

  { id: "risoto-abobora", meal: "almoco", name: "Risoto leve de abóbora (sem vinho)", time: 40, portions: 3,
    tags: ["moderna", "sem vinho", "conforto"],
    ing: ["1 xícara de arroz arbóreo (ou branco comum)", "2 xícaras de abóbora em cubos", "1 litro de caldo caseiro de legumes (sem cubo!)", "1/2 cebola picada", "2 col. de ricota", "Sal e salsinha"],
    steps: ["Cozinhe a abóbora no caldo até amolecer; amasse metade dela no próprio caldo.",
      "Refogue a cebola no fio de azeite, junte o arroz e vá adicionando o caldo aos poucos, mexendo.",
      "Quando o arroz estiver al dente (± 18 min), junte os cubos restantes de abóbora.",
      "Finalize com a ricota e a salsinha — cremosidade sem creme de leite."],
    tip: "O vinho do risoto tradicional é ácido — o caldo caseiro substitui sem dó." },

  // ---------- JANTAR ----------
  { id: "sopa-abobora", meal: "janta", name: "Sopa creme de abóbora com gengibre suave", time: 30, portions: 3,
    tags: ["leve", "para crises", "conforto"],
    ing: ["500 g de abóbora cabotiá em cubos", "1 rodela fina de gengibre", "1/2 cebola", "600 ml de água", "Sal e cebolinha"],
    steps: ["Refogue a cebola no fio de azeite, junte a abóbora, o gengibre e a água.",
      "Cozinhe 15–20 min até a abóbora desmanchar.",
      "Bata no liquidificador (retire o gengibre se preferir mais suave).",
      "Sirva com cebolinha picada."],
    tip: "Jantar líquido e morno é o melhor amigo de quem tem refluxo noturno." },

  { id: "canja", meal: "janta", name: "Canja de galinha clássica", time: 40, portions: 4,
    tags: ["clássica", "para crises", "conforto"],
    ing: ["1 peito de frango", "1/2 xícara de arroz", "1 cenoura em cubinhos", "1 batata em cubos", "1/2 cebola, sal, louro e salsinha", "1,5 litro de água"],
    steps: ["Cozinhe o frango com a cebola, o louro e a água por 20 min; retire e desfie.",
      "No mesmo caldo, cozinhe o arroz, a cenoura e a batata por 15 min.",
      "Volte o frango desfiado, acerte o sal e finalize com salsinha."],
    tip: "A receita da vovó é oficialmente aprovada pela gastroenterologia." },

  { id: "omelete-forno", meal: "janta", name: "Omelete de forno com legumes", time: 30, portions: 2,
    tags: ["forno", "proteica", "aproveitamento"],
    ing: ["4 ovos", "1/2 abobrinha ralada", "1/2 cenoura ralada", "2 col. de ricota", "Sal, orégano e salsinha"],
    steps: ["Bata os ovos com o sal e o orégano.",
      "Misture os legumes ralados e a ricota esfarelada.",
      "Despeje em forma untada com fio de azeite e asse a 180 °C por 20 min, até firmar e dourar de leve."],
    tip: "Aceita qualquer legume permitido que sobrou na geladeira." },

  { id: "pure-cara", meal: "janta", name: "Purê de cará com frango dourado", time: 30, portions: 2,
    tags: ["raízes", "conforto"],
    ing: ["3 carás médios", "1 xícara de frango desfiado", "Sal, cúrcuma e cebolinha", "1 fio de azeite"],
    steps: ["Cozinhe o cará descascado até amolecer e amasse com sal (use água do cozimento para dar cremosidade).",
      "Na antiaderente, doure o frango desfiado com o fio de azeite e a cúrcuma até ficar levemente crocante.",
      "Sirva o frango por cima do purê, com cebolinha."],
    tip: "Cará e inhame são intercambiáveis — use o que achar na feira." },

  { id: "sopa-legumes", meal: "janta", name: "Sopa de legumes com músculo desfiado", time: 50, portions: 4,
    tags: ["panela de pressão", "completa"],
    ing: ["300 g de músculo", "1 batata, 1 cenoura, 1 chuchu e 1 pedaço de abóbora em cubos", "1/2 cebola, sal e louro", "Salsinha"],
    steps: ["Cozinhe o músculo na pressão com a cebola, o louro e água por 30 min; desfie.",
      "No caldo, cozinhe os legumes por 10–15 min.",
      "Volte a carne desfiada, acerte o sal e sirva com salsinha."],
    tip: "Congele em potes individuais: jantar pronto para a semana inteira." },

  { id: "tilapia-pure", meal: "janta", name: "Tilápia grelhada com purê de mandioquinha", time: 30, portions: 2,
    tags: ["leve", "rápida"],
    ing: ["2 filés de tilápia", "3 mandioquinhas", "Sal, ervas finas e 1 fio de azeite", "Salsinha"],
    steps: ["Cozinhe a mandioquinha e amasse com sal até virar um purê sedoso.",
      "Tempere os filés e grelhe na antiaderente 3 min por lado, com cuidado para não desmanchar.",
      "Monte o prato e finalize com salsinha e o fio de azeite."],
    tip: "Peixe branco à noite = digestão tranquila antes de dormir." },

  // ---------- LANCHES & CEIA ----------
  { id: "banana-aveia", meal: "lanche", name: "Banana amassada com aveia e canela", time: 3, portions: 1,
    tags: ["rápida", "3 ingredientes"],
    ing: ["1 banana madura", "1 col. (sopa) de aveia", "Canela suave"],
    steps: ["Amasse a banana, misture a aveia e polvilhe a canela.", "Pronto. Sério."],
    tip: "O lanche de 3 minutos que salva a fome da tarde sem apelar para besteira." },

  { id: "iogurte-mamao", meal: "lanche", name: "Iogurte natural com mamão e mel", time: 5, portions: 1,
    tags: ["rápida", "probiótica"],
    ing: ["1 pote de iogurte natural desnatado", "2 col. de mamão em cubos", "1 col. (chá) de mel", "1 col. de aveia (opcional)"],
    steps: ["Monte em camadas num copo: iogurte, mamão, mel e aveia.", "Sirva gelado."],
    tip: "Probióticos do iogurte + papaína do mamão = dupla digestiva." },

  { id: "maca-airfryer", meal: "lanche", name: "Maçã assada na airfryer com canela", time: 15, portions: 1,
    tags: ["airfryer", "sobremesa saudável"],
    ing: ["1 maçã", "1 col. (chá) de mel", "Canela suave", "1 col. de aveia (opcional)"],
    steps: ["Corte a maçã ao meio e retire as sementes.",
      "Regue com o mel e polvilhe a canela.",
      "Airfryer a 160 °C por 12 min, até ficar macia e perfumada."],
    tip: "Mata a vontade de doce sem chocolate e sem culpa." },

  { id: "gelatina-frutas", meal: "lanche", name: "Gelatina com frutas permitidas", time: 10, portions: 4,
    tags: ["geladeira", "leve"],
    ing: ["1 pacote de gelatina (sabor suave, ex.: pêssego)", "1 banana em rodelas", "2 col. de mamão em cubos"],
    steps: ["Prepare a gelatina conforme a embalagem.",
      "Distribua as frutas em potinhos e despeje a gelatina morna por cima.",
      "Geladeira por 3 horas."],
    tip: "Sobremesa gelada segura para depois do almoço de domingo." },

  { id: "cha-espinheira", meal: "lanche", name: "Chá de espinheira-santa (preparo correto)", time: 15, portions: 1,
    tags: ["chá terapêutico", "fitoterápico"],
    ing: ["1 col. (sopa) de folhas secas de espinheira-santa", "1 xícara (200 ml) de água filtrada"],
    steps: ["Ferva a água e desligue o fogo.",
      "Adicione as folhas, tampe e abafe por 10 minutos.",
      "Coe e tome morno, de preferência 30 min antes das refeições.",
      "Use 2–3 xícaras ao dia, por períodos de até 4 semanas, com acompanhamento."],
    tip: "⚠️ Contraindicado para gestantes e lactantes. Converse com seu médico antes de usar diariamente." },
];

/* =========================================================
   SAFRA — produtos da estação por mês (calendário aproximado,
   base CEAGESP/Sudeste; varia conforme a região)
   ========================================================= */
const SEASONAL = [
  { frutas: ["Banana-prata", "Mamão", "Melão", "Uva niágara doce", "Figo", "Pera-d'água"],
    legumes: ["Abobrinha", "Pepino", "Beterraba", "Milho-verde", "Vagem", "Alface"] },
  { frutas: ["Banana-nanica", "Mamão-formosa", "Goiaba", "Uva itália", "Pera", "Maçã-gala"],
    legumes: ["Abóbora-menina", "Abobrinha", "Berinjela", "Chuchu", "Quiabo", "Alface"] },
  { frutas: ["Banana-maçã", "Goiaba", "Mamão", "Maçã-fuji", "Caqui doce", "Coco-verde"],
    legumes: ["Abóbora-japonesa", "Berinjela", "Beterraba", "Chuchu", "Couve", "Milho-verde"] },
  { frutas: ["Caqui doce", "Banana", "Goiaba", "Maçã", "Pera-portuguesa", "Mamão"],
    legumes: ["Abóbora", "Batata-doce", "Berinjela", "Brócolis", "Chuchu", "Mandioquinha"] },
  { frutas: ["Banana", "Caqui", "Maçã", "Mamão", "Melão", "Abacate"],
    legumes: ["Abóbora", "Batata-doce", "Brócolis", "Cará", "Inhame", "Mandioquinha"] },
  { frutas: ["Banana", "Maçã", "Mamão", "Melão", "Pera", "Abacate"],
    legumes: ["Abóbora", "Batata-doce", "Brócolis", "Cará", "Cenoura", "Inhame"] },
  { frutas: ["Banana", "Maçã", "Mamão-formosa", "Melão-amarelo", "Pera"],
    legumes: ["Abóbora-cabotiá", "Batata-doce", "Cará", "Cenoura", "Couve-flor", "Inhame", "Mandioquinha"] },
  { frutas: ["Banana", "Mamão", "Melão", "Maçã", "Pera"],
    legumes: ["Abobrinha", "Batata-doce", "Beterraba", "Cenoura", "Chuchu", "Couve", "Inhame"] },
  { frutas: ["Banana", "Mamão", "Melão", "Melancia", "Pera"],
    legumes: ["Abobrinha", "Beterraba", "Cenoura", "Chuchu", "Couve", "Vagem"] },
  { frutas: ["Banana", "Mamão", "Melão", "Melancia", "Manga madura"],
    legumes: ["Abobrinha", "Beterraba", "Cenoura", "Pepino", "Vagem", "Alface"] },
  { frutas: ["Banana", "Mamão", "Melancia", "Melão", "Manga", "Figo"],
    legumes: ["Abobrinha", "Beterraba", "Milho-verde", "Pepino", "Vagem", "Alface"] },
  { frutas: ["Banana", "Mamão", "Melancia", "Manga", "Figo", "Uva doce"],
    legumes: ["Abobrinha", "Beterraba", "Milho-verde", "Pepino", "Vagem", "Alface"] },
];

/* =========================================================
   DICAS — educação em pequenas doses
   ========================================================= */
const TIPS = [
  { cat: "Alimentação", icon: "🍽️", title: "Coma a cada 3 horas",
    text: "Porções pequenas e frequentes evitam tanto o estômago vazio (que dói) quanto o muito cheio (que reflui). Use os alarmes do app para criar o hábito." },
  { cat: "Alimentação", icon: "🐢", title: "Mastigue devagar — de verdade",
    text: "Mastigue cada garfada 20–30 vezes e apoie os talheres entre uma e outra. A digestão começa na boca, e comer rápido engole ar e sobrecarrega o estômago." },
  { cat: "Alimentação", icon: "💧", title: "Água entre as refeições, não durante",
    text: "Grandes volumes de líquido junto com a comida distendem o estômago. Beba pequenos goles ao longo do dia e evite copos cheios durante as refeições." },
  { cat: "Alimentação", icon: "🌡️", title: "Prefira comida morna",
    text: "Alimentos muito quentes ou muito gelados irritam a mucosa inflamada. Morno é a temperatura da recuperação." },
  { cat: "Refluxo noturno", icon: "🛏️", title: "Última refeição 3 horas antes de deitar",
    text: "Deitar com o estômago cheio é receita de refluxo noturno. Jante cedo e leve — o app avisa se seu jantar está muito perto do horário de dormir." },
  { cat: "Refluxo noturno", icon: "📐", title: "Eleve a cabeceira da cama (10–15 cm)",
    text: "Calços sob os pés da cabeceira ou travesseiro anti-refluxo (em cunha) usam a gravidade a seu favor. Empilhar travesseiros comuns não funciona — dobra o abdômen e piora." },
  { cat: "Refluxo noturno", icon: "🧭", title: "Durma do lado esquerdo",
    text: "Nessa posição, a entrada do estômago fica acima do nível do ácido, dificultando o refluxo. Pequeno truque, grande diferença." },
  { cat: "Estilo de vida", icon: "👖", title: "Evite roupas apertadas na cintura",
    text: "Cintos e calças justas pressionam o abdômen e empurram o ácido para cima, principalmente depois de comer." },
  { cat: "Estilo de vida", icon: "⚖️", title: "Perder peso reduz o refluxo",
    text: "Se há sobrepeso, cada quilo a menos diminui a pressão sobre o estômago. Acompanhe sua evolução na aba Peso & Metas." },
  { cat: "Estilo de vida", icon: "🚭", title: "Cigarro é inimigo direto",
    text: "A nicotina relaxa a válvula do esôfago e reduz a saliva que protege a mucosa. Parar de fumar melhora a gastrite e o refluxo." },
  { cat: "Estilo de vida", icon: "🧘", title: "Cuide da 'gastrite nervosa'",
    text: "Estresse e ansiedade aumentam a acidez. Caminhada leve, respiração profunda (4 s inspira, 6 s solta) e o chá de camomila da noite são tratamento também." },
  { cat: "Estilo de vida", icon: "🚶", title: "Caminhe após as refeições — não deite",
    text: "Uma caminhada leve de 10 minutos ajuda o esvaziamento do estômago. Deitar no sofá logo após comer tem o efeito oposto." },
  { cat: "Tratamento", icon: "💊", title: "Remédio na hora certa funciona melhor",
    text: "Omeprazol e similares (IBPs) agem melhor em jejum, 30–60 min antes do café da manhã. Configure o lembrete no app e siga SEMPRE a orientação do seu médico." },
  { cat: "Tratamento", icon: "📔", title: "Registre para descobrir seus gatilhos",
    text: "Cada pessoa reage diferente. Use o Diário: anote o que comeu e os sintomas — em 2 semanas os padrões aparecem e você descobre os SEUS gatilhos." },
  { cat: "Tratamento", icon: "🩺", title: "Sinais de alerta — procure o médico",
    text: "Dor intensa, vômitos persistentes, dificuldade para engolir, emagrecimento sem explicação, fezes escuras ou sangue: não espere, procure atendimento." },
];

const DEFAULT_MEALS = [
  { id: "m-cafe",    name: "Café da manhã", time: "07:00", alarm: true, icon: "🌅" },
  { id: "m-lanche1", name: "Lanche da manhã", time: "10:00", alarm: true, icon: "🍎" },
  { id: "m-almoco",  name: "Almoço", time: "12:30", alarm: true, icon: "🍽️" },
  { id: "m-lanche2", name: "Lanche da tarde", time: "15:30", alarm: true, icon: "🥪" },
  { id: "m-janta",   name: "Jantar", time: "18:30", alarm: true, icon: "🌙" },
  { id: "m-ceia",    name: "Ceia leve", time: "20:30", alarm: false, icon: "🍵" },
];

const SYMPTOMS = [
  { id: "azia",     name: "Azia / queimação", icon: "🔥" },
  { id: "refluxo",  name: "Refluxo / regurgitação", icon: "🌊" },
  { id: "dor",      name: "Dor no estômago", icon: "😖" },
  { id: "nausea",   name: "Náusea / enjoo", icon: "🤢" },
  { id: "estufado", name: "Estufamento / gases", icon: "🎈" },
  { id: "garganta", name: "Garganta irritada / tosse", icon: "😮‍💨" },
];

const GOAL_SUGGESTIONS = [
  "30 dias sem café",
  "Jantar 3h antes de dormir",
  "Zero fritura esta semana",
  "Chá calmante toda noite",
  "Mastigar devagar em todas as refeições",
  "Caminhar 10 min após o almoço",
  "Sem chocolate por 21 dias",
  "Sem refrigerante por 30 dias",
];

const MONTH_NAMES = ["Janeiro","Fevereiro","Março","Abril","Maio","Junho",
  "Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"];
